JSON2Batch: parsing::JsonHandler Class Reference
parsing::JsonHandler Class Reference
This file reads all data from the json file.
#include <JsonHandler.hpp>
Public Member Functions
JsonHandler ()
Constructor without arguments.
JsonHandler (const std::string &filename)
The constructor.
std::shared_ptr< FileData > getFileData ()
Retrieve the data from the json file.
Private Member Functions
void assignOutputFile () const
Assigns the outputfile to this->data.
void assignHideShell () const
Assigns the hideshell value to this->data.
void assignApplication () const
Assigns application to this->data.
void assignEntries () const
Assigns entries to this->data.
void assignCommand (const Json::Value &entry) const
Assigns an command to this->data.
void assignEnvironmentVariable (const Json::Value &entry) const
Assigns an environmentVariable to this->data.
void assignPathValue (const Json::Value &entry) const
Assigns a path value to this->data.
std::shared_ptr< FileData > createFileData ()
Creates the FileData instance.
Static Private Member Functions
static std::shared_ptr< Json::Value > parseFile (const std::string &filename)
Parses the given json file.
static bool containsBadCharacter (const std::string_view &str)
Check if a string contains a bad character.
Private Attributes
std::shared_ptr< Json::Value > root
std::shared_ptr< FileData > data
Detailed Description
This file reads all data from the json file.
This file uses the jsoncpp library to parse all data from a json file, validate it to some degree.
See also
https://github.com/open-source-parsers/jsoncpp
Definition at line 47 of file JsonHandler.hpp.
Constructor & Destructor Documentation
JsonHandler() [1/2]
parsing::JsonHandler::JsonHandler () inline
Constructor without arguments.
This constructor can be used to initialise an instance in an outer scope and then assign it values from an inner scope.
Definition at line 55 of file JsonHandler.hpp.
JsonHandler() [2/2]
parsing::JsonHandler::JsonHandler (const std::string & filename) explicit
The constructor.
This constructor calls this->parseFile() when called.
Parameters
filename Name of the json file
Definition at line 23 of file JsonHandler.cpp.
References parseFile(), and root.
Member Function Documentation
assignApplication()
void parsing::JsonHandler::assignApplication () const private
Assigns application to this->data.
Retrieves the value of the application key from Json::Value this->root and defaults to an empty string.
{ReqFunc16}
Definition at line 84 of file JsonHandler.cpp.
References containsBadCharacter(), data, utilities::Utils::escapeString(), and root.
assignCommand()
void parsing::JsonHandler::assignCommand (const Json::Value & entry) const private
Assigns an command to this->data.
{ReqFunc12}
Parameters
entry The entry with the command
Definition at line 118 of file JsonHandler.cpp.
References containsBadCharacter(), data, and utilities::Utils::escapeString().
assignEntries()
void parsing::JsonHandler::assignEntries () const private
Assigns entries to this->data.
Goes through each of the entries from Json::Value this->root and calls the relevant method depending on it's type. All "type" keys should be valid by this point.
{ReqFunc10}
Parameters
entry Json::Value containing an array with entries
Exceptions
exceptions::UnreachableCodeException
Definition at line 94 of file JsonHandler.cpp.
References assignCommand(), assignEnvironmentVariable(), assignPathValue(), and root.
assignEnvironmentVariable()
void parsing::JsonHandler::assignEnvironmentVariable (const Json::Value & entry) const private
Assigns an environmentVariable to this->data.
{ReqFunc11}
Parameters
entry The entry with the environmentVariable
Definition at line 128 of file JsonHandler.cpp.
References containsBadCharacter(), data, and utilities::Utils::escapeString().
assignHideShell()
void parsing::JsonHandler::assignHideShell () const private
Assigns the hideshell value to this->data.
Retrieves the value of the hideshell key from Json::Value this->root and defaults to negative.
{ReqFunc9}
Definition at line 78 of file JsonHandler.cpp.
References data, and root.
assignOutputFile()
void parsing::JsonHandler::assignOutputFile () const private
Assigns the outputfile to this->data.
Retrieves the outputfile from Json::Value this->root and makes sure, that the file doesn't already exist.
{ReqFunc8}
Exceptions
exceptions::FileExistsException
Definition at line 68 of file JsonHandler.cpp.
References containsBadCharacter(), data, utilities::Utils::escapeString(), and root.
assignPathValue()
void parsing::JsonHandler::assignPathValue (const Json::Value & entry) const private
Assigns a path value to this->data.
{ReqFunc13}
Parameters
entry The entry with the path value
Definition at line 144 of file JsonHandler.cpp.
References containsBadCharacter(), data, and utilities::Utils::escapeString().
containsBadCharacter()
bool parsing::JsonHandler::containsBadCharacter (const std::string_view & str) static private
Check if a string contains a bad character.
This method checks if a given string contains a bad character. Bad characters are declared in a set within the function. This is done to ensure, that no characters such as line breaks, break the later generated batch file.
Parameters
str The string to be checked
@bool If the string contains a bad char or not
Definition at line 154 of file JsonHandler.cpp.
createFileData()
std::shared_ptr< FileData > parsing::JsonHandler::createFileData () private
Creates the FileData instance.
Instantiates the FileData instance, calls all nessecary functions and returns a shared pointer to it.
Returns
Pointer to the created instance of FileData
Definition at line 58 of file JsonHandler.cpp.
References assignApplication(), assignEntries(), assignHideShell(), assignOutputFile(), and data.
getFileData()
std::shared_ptr< FileData > parsing::JsonHandler::getFileData ()
Retrieve the data from the json file.
This method calls this->createFileData() needed to retrieve the values from the Json::Value this->root and then returns a shared pointer to the created FileData object.
Returns
Pointer to the FileData Object with the parsed data from json
Definition at line 53 of file JsonHandler.cpp.
References createFileData().
parseFile()
std::shared_ptr< Json::Value > parsing::JsonHandler::parseFile (const std::string & filename) static private
Parses the given json file.
This method first creates a new Json::Value instance and then tries to parse the given json file. It then validates the keys of the instance using the KeyValidator class.
Parameters
filename The name of the file wich should be parsed
Returns
A shared pointer to the Json::Value instance
See also
KeyValidator::validateKeys()
Exceptions
exceptions::ParsingException
exceptions::InvalidKeyException
Definition at line 28 of file JsonHandler.cpp.
References parsing::KeyValidator::getInstance().
Member Data Documentation
data
std::shared_ptr<FileData> parsing::JsonHandler::data private
Definition at line 179 of file JsonHandler.hpp.
root
std::shared_ptr<Json::Value> parsing::JsonHandler::root private
Definition at line 178 of file JsonHandler.hpp.
The documentation for this class was generated from the following files:
src/include/JsonHandler.hpp
src/sources/JsonHandler.cpp