JSON2Batch: parsing::KeyValidator Class Reference
parsing::KeyValidator Class Reference
Validates keys of a Json::Value object.
#include <KeyValidator.hpp>
Public Member Functions
std::vector< std::tuple< int, std::string > > validateKeys (const Json::Value &root, const std::string &filename)
Validate keys off a Json::Value object.
Static Public Member Functions
static KeyValidator & getInstance ()
Get the instance of this class.
Private Member Functions
std::vector< std::tuple< int, std::string > > getWrongKeys (const Json::Value &root, const std::string &filename) const
Retrieve the wrong keys from a Json::Value object.
void validateTypes (const std::string &filename, const Json::Value &entry, const std::unordered_set< std::string > &entryKeys)
Validates types from the entries array.
std::vector< std::tuple< int, std::string > > validateEntries (const std::string &filename, const std::unordered_set< std::string > &entryKeys) const
Validates that keys within the entries array are valid.
Static Private Member Functions
static std::optional< int > getUnknownKeyLine (const std::string &filename, const std::string &wrongKey)
Get the line of an unknown key.
Private Attributes
std::unordered_set< std::string > validKeys
std::unordered_set< std::string > validEntryKeys
std::unordered_map< std::string_view, std::vector< std::string > > typeToKeys
Detailed Description
Validates keys of a Json::Value object.
This class is singleton. That way when multiple files are parsed with the application, the maps for valid keys and the set for the type entries field only have to be allocated once when parsing multiple files.
Definition at line 30 of file KeyValidator.hpp.
Member Function Documentation
getInstance()
KeyValidator & parsing::KeyValidator::getInstance () static
Get the instance of this class.
Returns
Reference to the instance of this class
Definition at line 20 of file KeyValidator.cpp.
getUnknownKeyLine()
std::optional< int > parsing::KeyValidator::getUnknownKeyLine (const std::string & filename, const std::string & wrongKey) static private
Get the line of an unknown key.
This method goes through each line of the given file and checks if the line contains the given key. Returns std::nullopt if the file can't be opened or the key was not found.
Parameters
filename The filename which should contain the key
wrongKey The key to be searched for
Returns
The line of the key, if it was found
Definition at line 129 of file KeyValidator.cpp.
getWrongKeys()
std::vector< std::tuple< int, std::string > > parsing::KeyValidator::getWrongKeys (const Json::Value & root, const std::string & filename) const private
Retrieve the wrong keys from a Json::Value object.
This method goes through each key of the Json::Value object and makes sure it's valid.
Parameters
root The Json::Value object to be validated.
filename The filename from which 'root' is from.
Returns
A vector with tuples, containing the line and name of invalid types.
Definition at line 51 of file KeyValidator.cpp.
References getUnknownKeyLine(), and validKeys.
validateEntries()
std::vector< std::tuple< int, std::string > > parsing::KeyValidator::validateEntries (const std::string & filename, const std::unordered_set< std::string > & entryKeys) const private
Validates that keys within the entries array are valid.
This mehthod goes through each of the entries, and validates, that the keys are part of the validEntryKeys attribute.
Parameters
filename The filename from which the entries are from
entryKeys The keys of the entries
Returns
A vector with tuples, containing the line and name of invalid entrie keys
Definition at line 74 of file KeyValidator.cpp.
References getUnknownKeyLine(), and validEntryKeys.
validateKeys()
std::vector< std::tuple< int, std::string > > parsing::KeyValidator::validateKeys (const Json::Value & root, const std::string & filename)
Validate keys off a Json::Value object.
This method goes through the MemberNames of a Json::Value object and validates, that they are part of the validKey attribute. It calls the nessecary methods to validate the keys within the entries array.
Parameters
root The Json::Value object to be validated.
filename The filename from which 'root' is from.
Returns
A vector with tuples, containing the line and name of invalid types.
Definition at line 27 of file KeyValidator.cpp.
References getWrongKeys(), validateEntries(), and validateTypes().
validateTypes()
void parsing::KeyValidator::validateTypes (const std::string & filename, const Json::Value & entry, const std::unordered_set< std::string > & entryKeys) private
Validates types from the entries array.
This method goes makes sure, that the type of the given entry is valid and that it contains it's necessary keys. It will throw an exception if the type is missing, if the type is invalid or if the type is missing a key.
Note
Unnecessary keys within a type entry, don't cause an exception and are ignored.
Parameters
filename The filename from which 'entry' is from
entry The entry to be validated
entryKeys The keys of the entry
Exceptions
exceptions::MissingTypeException
exceptions::InvalidTypeException
exceptions::MissingKeyException
Definition at line 96 of file KeyValidator.cpp.
References getUnknownKeyLine(), and typeToKeys.
Member Data Documentation
typeToKeys
std::unordered_map<std::string_view, std::vector<std::string> > parsing::KeyValidator::typeToKeys private
Initial value:
= {
        {"EXE", {"command"}}, {"PATH", {"path"}}, {"ENV", {"key", "value"}}
    }
Note
Changed from if/else clause within function to map in 0.2.1
Definition at line 144 of file KeyValidator.hpp.
validEntryKeys
std::unordered_set<std::string> parsing::KeyValidator::validEntryKeys private
Initial value:
= {"type", "key", "value",
        "path", "command"
    }
Note
Changed from vector to unordered_set in 0.2.1 - as this shoud improve lookup performance from O(n) to O(1)
Definition at line 137 of file KeyValidator.hpp.
validKeys
std::unordered_set<std::string> parsing::KeyValidator::validKeys private
Initial value:
= {"outputfile", "hideshell",
        "entries", "application"
    }
Note
Changed from vector to unordered_set in 0.2.1 - as this shoud improve lookup performance from O(n) to O(1)
Definition at line 130 of file KeyValidator.hpp.
The documentation for this class was generated from the following files:
src/include/KeyValidator.hpp
src/sources/KeyValidator.cpp