JSON2Batch: cli::CommandLineHandler Class Reference
cli::CommandLineHandler Class Reference
Responsible for the Command Line Interface.
#include <CommandLineHandler.hpp>
Public Member Functions
CommandLineHandler ()=delete
The Constructor of the CommandLineHandler Class.
~CommandLineHandler ()=delete
The Destructor of the CommandLineHandler Class.
Static Public Member Functions
static void printHelp ()
Prints the help message.
static void printVersion ()
Prints the version message.
static void printCredits ()
Prints the credits message.
static std::tuple< std::optional< std::string >, std::vector< std::string > > parseArguments (int argc, char *argv[])
Parses the Command Line Arguments.
Detailed Description
Responsible for the Command Line Interface.
This class is responsible for parsing the command line arguments, printing Help/Version/Credits messages and returning inputted files.
Author
Simon Blum
Date
2024-04-18
Version
0.1.5
See also
options
Definition at line 55 of file CommandLineHandler.hpp.
Constructor & Destructor Documentation
CommandLineHandler()
cli::CommandLineHandler::CommandLineHandler () delete
The Constructor of the CommandLineHandler Class.
Note
As all functions are static it should not be used and as such is deleted.
~CommandLineHandler()
cli::CommandLineHandler::~CommandLineHandler () delete
The Destructor of the CommandLineHandler Class.
Note
As all functions are static it should not be used and as such is deleted.
Member Function Documentation
parseArguments()
std::tuple< std::optional< std::string >, std::vector< std::string > > cli::CommandLineHandler::parseArguments (int argc, char * argv[]) static
Parses the Command Line Arguments.
This function uses the "getopt.h" library to parse all options given and then returns all files which are given as arguments.
Parameters
argc The number of arguments given
argv The arguments given
Returns
Returns a tuple containing the output directory and the files
Definition at line 68 of file CommandLineHandler.cpp.
References printCredits(), printHelp(), and printVersion().
printCredits()
void cli::CommandLineHandler::printCredits () static
Prints the credits message.
Note
This function ends the application.
Definition at line 50 of file CommandLineHandler.cpp.
References config::AUTHORS, config::DESCRIPTION, config::HOMEPAGE_URL, config::MAJOR_VERSION, config::MINOR_VERSION, config::PATCH_VERSION, and config::PROJECT_NAME.
printHelp()
void cli::CommandLineHandler::printHelp () static
Prints the help message.
Note
This function ends the application.
Definition at line 22 of file CommandLineHandler.cpp.
References config::EXECUTABLE_NAME.
printVersion()
void cli::CommandLineHandler::printVersion () static
Prints the version message.
Note
This function ends the application.
Definition at line 44 of file CommandLineHandler.cpp.
References config::MAJOR_VERSION, config::MINOR_VERSION, config::PATCH_VERSION, and config::PROJECT_NAME.
The documentation for this class was generated from the following files:
src/include/CommandLineHandler.hpp
src/sources/CommandLineHandler.cpp