/**
 * @file config.hpp
 * @author Simon Blum
 * @date 2024-04-18
 * @version 0.1.5
 * @brief Configures general project information
 * @details
 * This file is used by CMake to configure general information which can be
 * used throughout the project.
 *
 * @note This file is automatically configured by CMake.
 *       The original file can be found in conf/config.hpp.in
 * @license GNU GPLv3
 * @copyright See LICENSE file
 */
// @AUTOGENERATED_WARNING@

#ifndef CONFIG_HPP
#define CONFIG_HPP
#define LOG_CONFIG "@LOG_CONFIG@"
#define MAJOR_VERSION "@PROJECT_VERSION_MAJOR@"
#define MINOR_VERSION "@PROJECT_VERSION_MINOR@"
#define PATCH_VERSION "@PROJECT_VERSION_PATCH@"
#define DESCRIPTION "@PROJECT_DESCRIPTION@"
#define PROJECT_NAME "@PROJECT_NAME@"
#define AUTHORS "@AUTHORS@"
#define HOMEPAGE_URL "@PROJECT_HOMEPAGE_URL@"
#endif
