.TH "src/include Directory Reference" 3 "Fri Apr 26 2024 15:08:02" "Version 0.2.4" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBatchCreator\&.hpp\fP"
.br
.RI "Contains the \fBBatchCreator\fP class\&. "
.ti -1c
.RI "file \fBCommandLineHandler\&.hpp\fP"
.br
.RI "Responsible for the Command Line Interface\&. "
.ti -1c
.RI "file \fBconfig\&.hpp\fP"
.br
.RI "Configures general project information\&. "
.ti -1c
.RI "file \fBExceptions\&.hpp\fP"
.br
.RI "Contains all the custom exceptions used in the project\&. "
.ti -1c
.RI "file \fBFileData\&.hpp\fP"
.br
.RI "This file contains the FileData class\&. "
.ti -1c
.RI "file \fBJsonHandler\&.hpp\fP"
.br
.RI "This file contains the JsonHandler class\&. "
.ti -1c
.RI "file \fBKeyValidator\&.hpp\fP"
.br
.RI "This file contains the KeyValidator class\&. "
.ti -1c
.RI "file \fBUtils\&.hpp\fP"
.br
.in -1c
