.TH "src/sources Directory Reference" 3 "Thu Apr 25 2024 10:54:40" "Version 0.2.1" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sources Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBatchCreator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCommandLineHandler\&.cpp\fP"
.br
.RI "Implementation for the Command Line Interface\&. "
.ti -1c
.RI "file \fBFileData\&.cpp\fP"
.br
.ti -1c
.RI "file \fBJsonHandler\&.cpp\fP"
.br
.ti -1c
.RI "file \fBKeyValidator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBUtils\&.cpp\fP"
.br
.RI "Implementation for the Utils class\&. "
.in -1c
