.TH "src/sources Directory Reference" 3 "Fri Apr 26 2024 14:22:44" "Version 0.2.2" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sources Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBatchCreator\&.cpp\fP"
.br
.RI "Contains the implementation of the \fBBatchCreator\fP class\&. "
.ti -1c
.RI "file \fBCommandLineHandler\&.cpp\fP"
.br
.RI "Implementation for the Command Line Interface\&. "
.ti -1c
.RI "file \fBFileData\&.cpp\fP"
.br
.RI "Implementation of the FileData class\&. "
.ti -1c
.RI "file \fBJsonHandler\&.cpp\fP"
.br
.RI "Implementation of the JsonHandler class\&. "
.ti -1c
.RI "file \fBKeyValidator\&.cpp\fP"
.br
.RI "Implementation for the KeyValidator class\&. "
.ti -1c
.RI "file \fBUtils\&.cpp\fP"
.br
.RI "Implementation for the Utils class\&. "
.in -1c
