.TH "src/sources/BatchCreator.cpp" 3 "Fri Apr 26 2024 14:40:03" "Version 0.2.3" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sources/BatchCreator.cpp \- Contains the implementation of the \fBBatchCreator\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'BatchCreator\&.hpp'\fP
.br
\fC#include 'LoggingWrapper\&.hpp'\fP
.br
\fC#include <utility>\fP
.br

.SH "Detailed Description"
.PP 
Contains the implementation of the \fBBatchCreator\fP class\&. 


.PP
\fBAuthor\fP
.RS 4
Maximilian Rodler 
.RE
.PP
\fBDate\fP
.RS 4
22\&.04\&.2024 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.2\&.2 
.RE
.PP
\fBSee also\fP
.RS 4
\fBsrc/include/BatchCreator\&.hpp\fP
.RE
.PP
\fBCopyright\fP
.RS 4
See LICENSE file 
.RE
.PP

.PP
Definition in file \fBBatchCreator\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
