.TH "src/sources/BatchCreator.cpp" 3 "Fri Apr 26 2024 09:28:43" "Version 0.2.2" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sources/BatchCreator.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'BatchCreator\&.hpp'\fP
.br
\fC#include 'LoggingWrapper\&.hpp'\fP
.br
\fC#include <utility>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
