.TH "BatchCreator" 3 "Sat Apr 27 2024 13:06:24" "Version 0.3.1" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BatchCreator \- Creates a batch file from a FileData obeject\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BatchCreator\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBatchCreator\fP (std::shared_ptr< \fBparsing::FileData\fP > \fBfileData\fP)"
.br
.RI "Initializes the \fBBatchCreator\fP\&. "
.ti -1c
.RI "std::shared_ptr< std::stringstream > \fBgetDataStream\fP () const"
.br
.RI "Returns the stringstream\&. "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBcreateBatch\fP () const"
.br
.RI "Creates the batch stream\&. "
.ti -1c
.RI "void \fBwriteStart\fP () const"
.br
.RI "Wirtes the start of the batch file\&. "
.ti -1c
.RI "void \fBwriteHideShell\fP () const"
.br
.RI "Writes the visibility of the shell\&. "
.ti -1c
.RI "void \fBwriteCommands\fP () const"
.br
.RI "Writes the commands to be executed\&. "
.ti -1c
.RI "void \fBwriteEnvVariables\fP () const"
.br
.RI "Set's environment variables\&. "
.ti -1c
.RI "void \fBwritePathVariables\fP () const"
.br
.RI "Set's the path variables\&. "
.ti -1c
.RI "void \fBwriteApplication\fP () const"
.br
.RI "If an application is given, it is started at the end\&. "
.ti -1c
.RI "void \fBwriteEnd\fP () const"
.br
.RI "Writes the end of the batch file\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::shared_ptr< std::stringstream > \fBdataStream\fP"
.br
.ti -1c
.RI "std::shared_ptr< \fBparsing::FileData\fP > \fBfileData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Creates a batch file from a FileData obeject\&. 

Uses a FileData object to create a string stream, which can then be streamed into a batch file\&.
.PP
\fBSee also\fP
.RS 4
FileData 
.RE
.PP

.PP
Definition at line \fB29\fP of file \fBBatchCreator\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BatchCreator::BatchCreator (std::shared_ptr< \fBparsing::FileData\fP > fileData)\fC [explicit]\fP"

.PP
Initializes the \fBBatchCreator\fP\&. Creates a stringstream and calls the \fBcreateBatch()\fP function
.PP
\fBParameters\fP
.RS 4
\fIfilenData\fP A shared pointer to the FileData object 
.RE
.PP

.PP
Definition at line \fB18\fP of file \fBBatchCreator\&.cpp\fP\&.
.PP
References \fBcreateBatch()\fP, and \fBdataStream\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void BatchCreator::createBatch () const\fC [private]\fP"

.PP
Creates the batch stream\&. < FileData object
.PP
The method calls all necessary functions to create the stream for the batch file\&. 
.PP
Definition at line \fB25\fP of file \fBBatchCreator\&.cpp\fP\&.
.PP
References \fBwriteApplication()\fP, \fBwriteCommands()\fP, \fBwriteEnd()\fP, \fBwriteEnvVariables()\fP, \fBwriteHideShell()\fP, \fBwritePathVariables()\fP, and \fBwriteStart()\fP\&.
.SS "std::shared_ptr< std::stringstream > BatchCreator::getDataStream () const\fC [inline]\fP"

.PP
Returns the stringstream\&. 
.PP
\fBReturns\fP
.RS 4
A shared pointer to the stringstream 
.RE
.PP

.PP
Definition at line \fB46\fP of file \fBBatchCreator\&.hpp\fP\&.
.PP
References \fBdataStream\fP\&.
.SS "void BatchCreator::writeApplication () const\fC [private]\fP"

.PP
If an application is given, it is started at the end\&. If the key 'application' is given in the json file, the application is started at the end of the batch file\&.
.IP "\(bu" 2
{ReqFunc16}
.IP "\(bu" 2
{ReqFunc25} 
.PP

.PP
Definition at line \fB81\fP of file \fBBatchCreator\&.cpp\fP\&.
.PP
References \fBdataStream\fP, and \fBfileData\fP\&.
.SS "void BatchCreator::writeCommands () const\fC [private]\fP"

.PP
Writes the commands to be executed\&. Writes the commands to be executed from the FileData object\&. Those originiate from the 'commands' entry in the json file
.IP "\(bu" 2
{ReqFunc20}
.IP "\(bu" 2
{ReqFunc22} 
.PP

.PP
Definition at line \fB53\fP of file \fBBatchCreator\&.cpp\fP\&.
.PP
References \fBdataStream\fP, and \fBfileData\fP\&.
.SS "void BatchCreator::writeEnd () const\fC [private]\fP"

.PP
Writes the end of the batch file\&. Writes the end of the batch file, which is always the same:
.IP "\(bu" 2
@ECHO ON 
.PP

.PP
Definition at line \fB99\fP of file \fBBatchCreator\&.cpp\fP\&.
.PP
References \fBdataStream\fP\&.
.SS "void BatchCreator::writeEnvVariables () const\fC [private]\fP"

.PP
Set's environment variables\&. Set's the envirment variables for the batch\&. Those originiate from the 'ENV' entry in the json file with the following syntax:
.IP "\(bu" 2
Entry under 'key' = Entry under 'value'
.IP "\(bu" 2
{ReqFunc20}
.IP "\(bu" 2
{ReqFunc21} 
.PP

.PP
Definition at line \fB62\fP of file \fBBatchCreator\&.cpp\fP\&.
.PP
References \fBdataStream\fP, and \fBfileData\fP\&.
.SS "void BatchCreator::writeHideShell () const\fC [private]\fP"

.PP
Writes the visibility of the shell\&. This hides/shows the shell after the batch file has been executed
.IP "\(bu" 2
{ReqFunc19} 
.PP

.PP
Definition at line \fB42\fP of file \fBBatchCreator\&.cpp\fP\&.
.PP
References \fBdataStream\fP, and \fBfileData\fP\&.
.SS "void BatchCreator::writePathVariables () const\fC [private]\fP"

.PP
Set's the path variables\&. Set's the path variables for the batch\&. Those originiate from the 'PATH' entry in the json file
.IP "\(bu" 2
{ReqFunc20}
.IP "\(bu" 2
{ReqFunc23} 
.PP

.PP
Definition at line \fB70\fP of file \fBBatchCreator\&.cpp\fP\&.
.PP
References \fBdataStream\fP, and \fBfileData\fP\&.
.SS "void BatchCreator::writeStart () const\fC [private]\fP"

.PP
Wirtes the start of the batch file\&. Writes the start of the batch file, which is always the same:
.IP "\(bu" 2
setzt ECHO off
.IP "\(bu" 2
startet cmd\&.exe 
.PP

.PP
Definition at line \fB36\fP of file \fBBatchCreator\&.cpp\fP\&.
.PP
References \fBdataStream\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::shared_ptr<std::stringstream> BatchCreator::dataStream\fC [private]\fP"

.PP
Definition at line \fB52\fP of file \fBBatchCreator\&.hpp\fP\&.
.SS "std::shared_ptr<\fBparsing::FileData\fP> BatchCreator::fileData\fC [private]\fP"
< stringstream for the batch file 
.PP
Definition at line \fB54\fP of file \fBBatchCreator\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
