.TH "src/include/BatchCreator.hpp" 3 "Fri Apr 26 2024 10:00:12" "Version 0.2.2" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/BatchCreator.hpp \- Creates batch file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'FileData\&.hpp'\fP
.br
\fC#include 'JsonHandler\&.hpp'\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBatchCreator\fP"
.br
.RI "Erstellt Batch Datei\&. "
.in -1c
.SH "Detailed Description"
.PP 
Creates batch file\&. 


.PP
\fBAuthor\fP
.RS 4
Maximilian Rodler 
.RE
.PP
\fBDate\fP
.RS 4
22\&.04\&.2024 
.RE
.PP
\fBVersion\fP
.RS 4
.RE
.PP
\fBCopyright\fP
.RS 4
See LICENSE file
.RE
.PP
\fBTodo\fP
.RS 4
Documentation in english 
.RE
.PP
.PP
\fBAuthor\fP
.RS 4
Maximilian Rodler 
.RE
.PP
\fBDate\fP
.RS 4
22\&.04\&.2024 
.RE
.PP
\fBVersion\fP
.RS 4
.RE
.PP
Creates batch file from Arguments in JSON
.PP
\fBCopyright\fP
.RS 4
See LICENSE file 
.RE
.PP

.PP
Definition in file \fBBatchCreator\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
