.TH "src/include/BatchCreator.hpp" 3 "Sat Apr 27 2024 12:13:46" "Version 0.2.5" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/BatchCreator.hpp \- Contains the \fBBatchCreator\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'FileData\&.hpp'\fP
.br
\fC#include <memory>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBatchCreator\fP"
.br
.RI "Creates a batch file from a FileData obeject\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains the \fBBatchCreator\fP class\&. 


.PP
\fBAuthor\fP
.RS 4
Maximilian Rodler 
.RE
.PP
\fBDate\fP
.RS 4
2024-04-22 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.2\&.1 
.RE
.PP
\fBSee also\fP
.RS 4
\fBBatchCreator\fP
.PP
\fBsrc/sources/BatchCreator\&.cpp\fP
.RE
.PP
\fBCopyright\fP
.RS 4
See LICENSE file 
.RE
.PP

.PP
Definition in file \fBBatchCreator\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
