.TH "cli" 3 "Fri Apr 26 2024 15:08:01" "Version 0.2.4" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cli \- Includes everything regarding the CLI\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommandLineHandler\fP"
.br
.RI "Responsible for the Command Line Interface\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const struct option \fBoptions\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Includes everything regarding the CLI\&. 

This namespace includes all the code regarding the Command Line Interface\&. This includes the \fBCommandLineHandler\fP Class, the struct for the options and helpers for Styling\&.
.PP
\fBSee also\fP
.RS 4
\fBCommandLineHandler\fP 
.PP
\fBoptions\fP 
.PP
\fBStyleHelpers\fP 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "const struct option cli::options[]\fC [static]\fP"
\fBInitial value:\fP.PP
.nf
= {
    {"help", no_argument, nullptr, 'h'}, 
    {"version", no_argument, nullptr, 'v'}, 
    {"credits", no_argument, nullptr, 'c'}, 
    {"verbose", no_argument, nullptr, 0}, 
    {"outdir", required_argument, nullptr, 'o'}, 
    nullptr
}
.fi

.PP
Definition at line \fB125\fP of file \fBCommandLineHandler\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
