.TH "cli::CommandLineHandler" 3 "Fri Apr 26 2024 12:28:19" "Version 0.2.2" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cli::CommandLineHandler \- Responsible for the Command Line Interface\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CommandLineHandler\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommandLineHandler\fP ()=delete"
.br
.RI "The Constructor of the \fBCommandLineHandler\fP Class\&. "
.ti -1c
.RI "\fB~CommandLineHandler\fP ()=delete"
.br
.RI "The Destructor of the \fBCommandLineHandler\fP Class\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBprintHelp\fP ()"
.br
.RI "Prints the help message\&. "
.ti -1c
.RI "static void \fBprintVersion\fP ()"
.br
.RI "Prints the version message\&. "
.ti -1c
.RI "static void \fBprintCredits\fP ()"
.br
.RI "Prints the credits message\&. "
.ti -1c
.RI "static std::tuple< std::optional< std::string >, std::vector< std::string > > \fBparseArguments\fP (int argc, char *argv[])"
.br
.RI "Parses the Command Line Arguments\&. "
.in -1c
.SH "Detailed Description"
.PP 
Responsible for the Command Line Interface\&. 

This class is responsible for parsing the command line arguments, printing Help/Version/Credits messages and returning inputted files\&.
.PP
\fBAuthor\fP
.RS 4
Simon Blum 
.RE
.PP
\fBDate\fP
.RS 4
2024-04-18 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1\&.5 
.RE
.PP
\fBSee also\fP
.RS 4
\fBoptions\fP 
.RE
.PP

.PP
Definition at line \fB55\fP of file \fBCommandLineHandler\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cli::CommandLineHandler::CommandLineHandler ()\fC [delete]\fP"

.PP
The Constructor of the \fBCommandLineHandler\fP Class\&. 
.PP
\fBNote\fP
.RS 4
As all functions are static it should not be used and as such is deleted\&. 
.RE
.PP

.SS "cli::CommandLineHandler::~CommandLineHandler ()\fC [delete]\fP"

.PP
The Destructor of the \fBCommandLineHandler\fP Class\&. 
.PP
\fBNote\fP
.RS 4
As all functions are static it should not be used and as such is deleted\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::tuple< std::optional< std::string >, std::vector< std::string > > cli::CommandLineHandler::parseArguments (int argc, char * argv[])\fC [static]\fP"

.PP
Parses the Command Line Arguments\&. This function uses the 'getopt\&.h' library to parse all options given and then returns all files which are given as arguments\&.
.PP
\fBParameters\fP
.RS 4
\fIargc\fP The number of arguments given 
.br
\fIargv\fP The arguments given
.RE
.PP
\fBReturns\fP
.RS 4
Returns a tuple containing the output directory and the files 
.RE
.PP

.PP
Definition at line \fB72\fP of file \fBCommandLineHandler\&.cpp\fP\&.
.PP
References \fBprintCredits()\fP, \fBprintHelp()\fP, and \fBprintVersion()\fP\&.
.SS "void cli::CommandLineHandler::printCredits ()\fC [static]\fP"

.PP
Prints the credits message\&. 
.PP
\fBNote\fP
.RS 4
This function ends the application\&. 
.RE
.PP

.PP
Definition at line \fB52\fP of file \fBCommandLineHandler\&.cpp\fP\&.
.PP
References \fBconfig::AUTHORS\fP, \fBconfig::DESCRIPTION\fP, \fBconfig::HOMEPAGE_URL\fP, \fBconfig::MAJOR_VERSION\fP, \fBconfig::MINOR_VERSION\fP, \fBconfig::PATCH_VERSION\fP, and \fBconfig::PROJECT_NAME\fP\&.
.SS "void cli::CommandLineHandler::printHelp ()\fC [static]\fP"

.PP
Prints the help message\&. 
.PP
\fBNote\fP
.RS 4
This function ends the application\&. 
.RE
.PP

.PP
Definition at line \fB22\fP of file \fBCommandLineHandler\&.cpp\fP\&.
.PP
References \fBconfig::EXECUTABLE_NAME\fP\&.
.SS "void cli::CommandLineHandler::printVersion ()\fC [static]\fP"

.PP
Prints the version message\&. 
.PP
\fBNote\fP
.RS 4
This function ends the application\&. 
.RE
.PP

.PP
Definition at line \fB45\fP of file \fBCommandLineHandler\&.cpp\fP\&.
.PP
References \fBconfig::MAJOR_VERSION\fP, \fBconfig::MINOR_VERSION\fP, \fBconfig::PATCH_VERSION\fP, and \fBconfig::PROJECT_NAME\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
