.TH "src/sources/CommandLineHandler.cpp" 3 "Sat Apr 27 2024 13:10:38" "Version 0.3.1" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sources/CommandLineHandler.cpp \- Implementation for the Command Line Interface\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'CommandLineHandler\&.hpp'\fP
.br
\fC#include 'LoggingWrapper\&.hpp'\fP
.br
\fC#include 'config\&.hpp'\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <getopt\&.h>\fP
.br
\fC#include <vector>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcli\fP"
.br
.RI "Includes everything regarding the CLI\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implementation for the Command Line Interface\&. 


.PP
\fBAuthor\fP
.RS 4
Simon Blum 
.RE
.PP
\fBDate\fP
.RS 4
2024-04-26 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.2\&.2 
.RE
.PP
\fBSee also\fP
.RS 4
src/include/utility/CommandLineHandler\&.hpp
.RE
.PP
\fBCopyright\fP
.RS 4
See LICENSE file 
.RE
.PP

.PP
Definition in file \fBCommandLineHandler\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
