.TH "src/include/CommandLineHandler.hpp" 3 "Fri Apr 26 2024 14:22:44" "Version 0.2.2" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/CommandLineHandler.hpp \- Responsible for the Command Line Interface\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <getopt\&.h>\fP
.br
\fC#include <optional>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcli::CommandLineHandler\fP"
.br
.RI "Responsible for the Command Line Interface\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcli\fP"
.br
.RI "Includes everything regarding the CLI\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const struct option \fBcli::options\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Responsible for the Command Line Interface\&. 


.PP
\fBAuthor\fP
.RS 4
Simon Blum 
.RE
.PP
\fBDate\fP
.RS 4
2024-04-26 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.2\&.2
.RE
.PP
This file is responsible for the Command Line Interface\&. As such it includes things such as the CommandLineHandler class, possible options and style helpers\&.
.PP
\fBSee also\fP
.RS 4
\fBcli\fP 
.PP
CommandLineHandler 
.PP
\fBoptions\fP 
.PP
\fBStyleHelpers\fP
.PP
\fBsrc/sources/CommandLineHandler\&.cpp\fP
.RE
.PP
\fBCopyright\fP
.RS 4
See LICENSE file 
.RE
.PP

.PP
Definition in file \fBCommandLineHandler\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
