.TH "src/include/config.hpp" 3 "Fri Apr 26 2024 13:19:44" "Version 0.2.2" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/config.hpp \- Configures general project information\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBconfig\fP"
.br
.RI "Namespace used for general project information\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr auto \fBconfig::LOG_CONFIG\fP"
.br
.ti -1c
.RI "constexpr auto \fBconfig::EXECUTABLE_NAME\fP = 'json2batch'"
.br
.ti -1c
.RI "constexpr auto \fBconfig::MAJOR_VERSION\fP = '0'"
.br
.ti -1c
.RI "constexpr auto \fBconfig::MINOR_VERSION\fP = '2'"
.br
.ti -1c
.RI "constexpr auto \fBconfig::PATCH_VERSION\fP = '2'"
.br
.ti -1c
.RI "constexpr auto \fBconfig::DESCRIPTION\fP = 'A simple tool to convert json to batch\&.'"
.br
.ti -1c
.RI "constexpr auto \fBconfig::PROJECT_NAME\fP = 'JSON2Batch'"
.br
.ti -1c
.RI "constexpr auto \fBconfig::AUTHORS\fP"
.br
.ti -1c
.RI "constexpr auto \fBconfig::HOMEPAGE_URL\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Configures general project information\&. 


.PP
\fBAuthor\fP
.RS 4
Simon Blum 
.RE
.PP
\fBDate\fP
.RS 4
2024-04-18 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1\&.5
.RE
.PP
This file is used by CMake to configure general information which can be used throughout the project\&.
.PP
\fBNote\fP
.RS 4
This file is automatically configured by CMake\&. The original file can be found in conf/config\&.hpp\&.in @license GNU GPLv3 
.RE
.PP
\fBCopyright\fP
.RS 4
See LICENSE file 
.RE
.PP

.PP
Definition in file \fBconfig\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
