.TH "config" 3 "Fri Apr 26 2024 13:01:11" "Version 0.2.2" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config \- Namespace used for general project information\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr auto \fBLOG_CONFIG\fP"
.br
.ti -1c
.RI "constexpr auto \fBEXECUTABLE_NAME\fP = 'json2batch'"
.br
.ti -1c
.RI "constexpr auto \fBMAJOR_VERSION\fP = '0'"
.br
.ti -1c
.RI "constexpr auto \fBMINOR_VERSION\fP = '2'"
.br
.ti -1c
.RI "constexpr auto \fBPATCH_VERSION\fP = '2'"
.br
.ti -1c
.RI "constexpr auto \fBDESCRIPTION\fP = 'A simple tool to convert json to batch\&.'"
.br
.ti -1c
.RI "constexpr auto \fBPROJECT_NAME\fP = 'JSON2Batch'"
.br
.ti -1c
.RI "constexpr auto \fBAUTHORS\fP"
.br
.ti -1c
.RI "constexpr auto \fBHOMEPAGE_URL\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Namespace used for general project information\&. 
.SH "Variable Documentation"
.PP 
.SS "constexpr auto config::AUTHORS\fC [inline]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
=
            "Elena Schwarzbach, Max Rodler, Simon Blum, Sonia Sinaci"
.fi

.PP
Definition at line \fB34\fP of file \fBconfig\&.hpp\fP\&.
.SS "constexpr auto config::DESCRIPTION = 'A simple tool to convert json to batch\&.'\fC [inline]\fP, \fC [constexpr]\fP"

.PP
Definition at line \fB32\fP of file \fBconfig\&.hpp\fP\&.
.SS "constexpr auto config::EXECUTABLE_NAME = 'json2batch'\fC [inline]\fP, \fC [constexpr]\fP"

.PP
Definition at line \fB28\fP of file \fBconfig\&.hpp\fP\&.
.SS "constexpr auto config::HOMEPAGE_URL\fC [inline]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
=
            "https://dhbwprojectsit23\&.github\&.io/JSON2Bat"
.fi

.PP
Definition at line \fB36\fP of file \fBconfig\&.hpp\fP\&.
.SS "constexpr auto config::LOG_CONFIG\fC [inline]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
= "/home/simon/1_Coding/projectJsonToBat/"
                                   "build/Release/config/easylogging\&.conf"
.fi

.PP
Definition at line \fB26\fP of file \fBconfig\&.hpp\fP\&.
.SS "constexpr auto config::MAJOR_VERSION = '0'\fC [inline]\fP, \fC [constexpr]\fP"

.PP
Definition at line \fB29\fP of file \fBconfig\&.hpp\fP\&.
.SS "constexpr auto config::MINOR_VERSION = '2'\fC [inline]\fP, \fC [constexpr]\fP"

.PP
Definition at line \fB30\fP of file \fBconfig\&.hpp\fP\&.
.SS "constexpr auto config::PATCH_VERSION = '2'\fC [inline]\fP, \fC [constexpr]\fP"

.PP
Definition at line \fB31\fP of file \fBconfig\&.hpp\fP\&.
.SS "constexpr auto config::PROJECT_NAME = 'JSON2Batch'\fC [inline]\fP, \fC [constexpr]\fP"

.PP
Definition at line \fB33\fP of file \fBconfig\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
