.TH "src/include/config.hpp" 3 "Thu Apr 25 2024 19:30:47" "Version 0.2.1" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/config.hpp \- Configures general project information\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLOG_CONFIG\fP   '/home/simon/1_Coding/projectJsonToBat/build/Release/config/easylogging\&.conf'"
.br
.ti -1c
.RI "#define \fBEXECUTABLE_NAME\fP   'json2batch'"
.br
.ti -1c
.RI "#define \fBMAJOR_VERSION\fP   '0'"
.br
.ti -1c
.RI "#define \fBMINOR_VERSION\fP   '2'"
.br
.ti -1c
.RI "#define \fBPATCH_VERSION\fP   '1'"
.br
.ti -1c
.RI "#define \fBDESCRIPTION\fP   'A simple tool to convert json to batch\&.'"
.br
.ti -1c
.RI "#define \fBPROJECT_NAME\fP   'JSON2Batch'"
.br
.ti -1c
.RI "#define \fBAUTHORS\fP   'Elena Schwarzbach, Max Rodler, Simon Blum, Sonia Sinaci'"
.br
.ti -1c
.RI "#define \fBHOMEPAGE_URL\fP   'https://definitelynotsimon13\&.github\&.io/ProjectJsonToBat'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Configures general project information\&. 


.PP
\fBAuthor\fP
.RS 4
Simon Blum 
.RE
.PP
\fBDate\fP
.RS 4
2024-04-18 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1\&.5
.RE
.PP
This file is used by CMake to configure general information which can be used throughout the project\&.
.PP
\fBNote\fP
.RS 4
This file is automatically configured by CMake\&. The original file can be found in conf/config\&.hpp\&.in @license GNU GPLv3 
.RE
.PP
\fBCopyright\fP
.RS 4
See LICENSE file 
.RE
.PP

.PP
Definition in file \fBconfig\&.hpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define AUTHORS   'Elena Schwarzbach, Max Rodler, Simon Blum, Sonia Sinaci'"

.PP
Definition at line \fB27\fP of file \fBconfig\&.hpp\fP\&.
.SS "#define DESCRIPTION   'A simple tool to convert json to batch\&.'"

.PP
Definition at line \fB25\fP of file \fBconfig\&.hpp\fP\&.
.SS "#define EXECUTABLE_NAME   'json2batch'"

.PP
Definition at line \fB21\fP of file \fBconfig\&.hpp\fP\&.
.SS "#define HOMEPAGE_URL   'https://definitelynotsimon13\&.github\&.io/ProjectJsonToBat'"

.PP
Definition at line \fB28\fP of file \fBconfig\&.hpp\fP\&.
.SS "#define LOG_CONFIG   '/home/simon/1_Coding/projectJsonToBat/build/Release/config/easylogging\&.conf'"

.PP
Definition at line \fB20\fP of file \fBconfig\&.hpp\fP\&.
.SS "#define MAJOR_VERSION   '0'"

.PP
Definition at line \fB22\fP of file \fBconfig\&.hpp\fP\&.
.SS "#define MINOR_VERSION   '2'"

.PP
Definition at line \fB23\fP of file \fBconfig\&.hpp\fP\&.
.SS "#define PATCH_VERSION   '1'"

.PP
Definition at line \fB24\fP of file \fBconfig\&.hpp\fP\&.
.SS "#define PROJECT_NAME   'JSON2Batch'"

.PP
Definition at line \fB26\fP of file \fBconfig\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
