.TH "exceptions" 3 "Fri Apr 26 2024 14:11:14" "Version 0.2.2" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exceptions \- Namespace used for customized exceptions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCustomException\fP"
.br
.RI "Base class for all custom exceptions\&. "
.ti -1c
.RI "class \fBFailedToOpenFileException\fP"
.br
.RI "Exception for when a file can't be opened\&. "
.ti -1c
.RI "class \fBFileExistsException\fP"
.br
.RI "Exception for an already exisiting outputfile\&. "
.ti -1c
.RI "class \fBInvalidKeyException\fP"
.br
.RI "Exception for invalid keys\&. "
.ti -1c
.RI "class \fBInvalidTypeException\fP"
.br
.RI "Exception for invalid types\&. "
.ti -1c
.RI "class \fBInvalidValueException\fP"
.br
.RI "Exception for an ivalid (usually empty) value field\&. "
.ti -1c
.RI "class \fBMissingKeyException\fP"
.br
.RI "Exception for missing keys within entries\&. "
.ti -1c
.RI "class \fBMissingTypeException\fP"
.br
.RI "Exception for missing types of entries\&. "
.ti -1c
.RI "class \fBNoSuchDirException\fP"
.br
.RI "Exception for when a directory does not exist\&. "
.ti -1c
.RI "class \fBParsingException\fP"
.br
.RI "Exception for syntax errors within the json file\&. "
.ti -1c
.RI "class \fBUnreachableCodeException\fP"
.br
.RI "Exception for when the application reaches code it shouldn't reach\&. "
.in -1c
.SH "Detailed Description"
.PP 
Namespace used for customized exceptions\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
