.TH "exceptions::UnreachableCodeException" 3 "Fri Apr 26 2024 15:23:50" "Version 0.2.4" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exceptions::UnreachableCodeException \- Exception for when the application reaches code it shouldn't reach\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Exceptions\&.hpp>\fP
.PP
Inherits \fBexceptions::CustomException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnreachableCodeException\fP (const std::string &\fBmessage\fP)"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const noexcept override"
.br
.in -1c

Public Member Functions inherited from \fBexceptions::CustomException\fP
.in +1c
.ti -1c
.RI "const char * \fBwhat\fP () const noexcept override"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBmessage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Exception for when the application reaches code it shouldn't reach\&. 
.PP
Definition at line \fB238\fP of file \fBExceptions\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "exceptions::UnreachableCodeException::UnreachableCodeException (const std::string & message)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line \fB243\fP of file \fBExceptions\&.hpp\fP\&.
.PP
References \fBconfig::EXECUTABLE_NAME\fP, and \fBmessage\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "const char * exceptions::UnreachableCodeException::what () const\fC [inline]\fP, \fC [override]\fP, \fC [noexcept]\fP"

.PP
Definition at line \fB250\fP of file \fBExceptions\&.hpp\fP\&.
.PP
References \fBmessage\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string exceptions::UnreachableCodeException::message\fC [private]\fP"

.PP
Definition at line \fB240\fP of file \fBExceptions\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
