.TH "src/sources/FileData.cpp" 3 "Fri Apr 26 2024 14:11:00" "Version 0.2.2" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sources/FileData.cpp \- Implementation of the FileData class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'FileData\&.hpp'\fP
.br
\fC#include 'Exceptions\&.hpp'\fP
.br
\fC#include 'LoggingWrapper\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBparsing\fP"
.br
.RI "The namespace containing everything relevant to parsing\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implementation of the FileData class\&. 


.PP
\fBAuthor\fP
.RS 4
Elena Schwarzbach, Sonia Sinacci 
.RE
.PP
\fBDate\fP
.RS 4
2024-04-26 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1\&.6 
.RE
.PP
\fBSee also\fP
.RS 4
\fBsrc/include/FileData\&.hpp\fP
.RE
.PP
\fBCopyright\fP
.RS 4
See LICENSE file 
.RE
.PP

.PP
Definition in file \fBFileData\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
