.TH "src/include/FileData.hpp" 3 "Sat Apr 27 2024 13:10:38" "Version 0.3.1" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/FileData.hpp \- This file contains the FileData class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <optional>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBparsing::FileData\fP"
.br
.RI "This class contains all data from the json file\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBparsing\fP"
.br
.RI "The namespace containing everything relevant to parsing\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file contains the FileData class\&. 


.PP
\fBAuthor\fP
.RS 4
Sonia Sinacci, Elena Schwartzbach 
.RE
.PP
\fBDate\fP
.RS 4
16\&.04\&.2024 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1\&.5 
.RE
.PP
\fBSee also\fP
.RS 4
\fBparsing::FileData\fP
.PP
\fBsrc/sources/FileData\&.cpp\fP
.RE
.PP
\fBCopyright\fP
.RS 4
See LICENSE file 
.RE
.PP

.PP
Definition in file \fBFileData\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
