.TH "src/include/KeyValidator.hpp" 3 "Fri Apr 26 2024 18:24:04" "Version 0.2.5" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/KeyValidator.hpp \- This file contains the KeyValidator class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'jsoncpp/value\&.h'\fP
.br
\fC#include <optional>\fP
.br
\fC#include <unordered_map>\fP
.br
\fC#include <unordered_set>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBparsing::KeyValidator\fP"
.br
.RI "Validates keys of a Json::Value object\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBparsing\fP"
.br
.RI "The namespace containing everything relevant to parsing\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file contains the KeyValidator class\&. 


.PP
\fBAuthor\fP
.RS 4
Simon Blum 
.RE
.PP
\fBDate\fP
.RS 4
2024-04-26 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.2\&.2 
.RE
.PP
\fBSee also\fP
.RS 4
\fBparsing::KeyValidator\fP
.PP
\fBsrc/sources/KeyValidator\&.cpp\fP
.RE
.PP
\fBCopyright\fP
.RS 4
See LICENSE file 
.RE
.PP

.PP
Definition in file \fBKeyValidator\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
