.TH "options" 3 "Fri Apr 26 2024 13:01:11" "Version 0.2.2" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
options \- The struct containing all possible options\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CommandLineHandler\&.hpp>\fP
.SH "Detailed Description"
.PP 
The struct containing all possible options\&. 

This struct contains all long and short options which can be used and will be parsed using 'getopt\&.h'
.PP
\fBSee also\fP
.RS 4
CommandLineHandler 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
