.TH "options" 3 "Sat Apr 27 2024 14:29:42" "Version 0.3.1" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
options \- The struct containing all possible options\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CommandLineHandler\&.hpp>\fP
.SH "Detailed Description"
.PP 
The struct containing all possible options\&. 

This struct contains all long and short options which can be used and will be parsed using 'getopt\&.h'
.IP "\(bu" 2
{ReqNonFunc4}
.PP
.PP
\fBSee also\fP
.RS 4
CommandLineHandler 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
