.TH "parsing" 3 "Thu Apr 25 2024 19:43:40" "Version 0.2.1" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parsing \- The namespace containing everything relevant to parsing\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFileData\fP"
.br
.RI "This class contains all data from the json file\&. "
.ti -1c
.RI "class \fBJsonHandler\fP"
.br
.RI "This file reads all data from the json file\&. "
.ti -1c
.RI "class \fBKeyValidator\fP"
.br
.RI "Validates keys of a Json::Value object\&. "
.in -1c
.SH "Detailed Description"
.PP 
The namespace containing everything relevant to parsing\&. 

This namespace contains all relevant classes to parsing the json file and creating the batch output\&.
.PP
\fBSee also\fP
.RS 4
\fBJsonHandler\fP 
.PP
\fBFileData\fP 
.PP
\fBKeyValidator\fP 
.PP
\fBBatchCreator\fP
.RE
.PP
\fBTodo\fP
.RS 4
Document -- map/set for efficient 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
