.TH "StyleHelpers" 3 "Fri Apr 26 2024 17:50:57" "Version 0.2.5" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StyleHelpers \- StyleHelpers
.PP
 \- Static variables to help with CLI styling\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Static variables to help with CLI styling\&. 

A group of strings, that use escape sequences to easily style the command line interface on Unix systems\&. When compiling for Windows all of these strings will be empty, as escape sequences can't be used the same way\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
