.TH "todo" 3 "Fri Apr 26 2024 13:01:17" "Version 0.2.2" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
.PP

.IP "\fBMember \fBBatchCreator::getDataStream\fP () const\fP" 1c
Documentation  
.IP "\fBMember \fBcli::CommandLineHandler::parseArguments\fP (int argc, char *argv[])\fP" 1c
Update documentation  
.IP "\fBMember \fBexceptions::FailedToOpenFileException::FailedToOpenFileException\fP (const std::string &file)\fP" 1c
Documentation  
.IP "\fBMember \fBexceptions::NoSuchDirException::NoSuchDirException\fP (const std::string &dir)\fP" 1c
Documentation  
.IP "\fBMember \fBmain\fP (int argc, char *argv[])\fP" 1c
Documentation 
.PP
.PP
Refactoring  
.IP "\fBpage \fBMain Page\fP \fP" 1c
Update \fBREADME\&.md\fP 
.IP "\fBNamespace \fBparsing\fP \fP" 1c
Document -- map/set for efficient  
.IP "\fBMember \fBparsing::KeyValidator::getUnknownKeyLine\fP (const std::string &filename, const std::string &wrongKey)\fP" 1c
Documentation  
.IP "\fBMember \fBparsing::KeyValidator::validateEntries\fP (const std::string &filename, const std::unordered_set< std::string > &entryKeys) const\fP" 1c
Documentation  
.IP "\fBMember \fButilities::Utils::checkDirectory\fP (std::string &directory)\fP" 1c
documentation 
.PP

