.TH "todo" 3 "Thu Apr 25 2024 17:35:57" "Version 0.2.1" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
.PP

.IP "\fBMember \fBBatchCreator::getDataStream\fP ()\fP" 1c
Documentation  
.IP "\fBMember \fBcli::CommandLineHandler::parseArguments\fP (int argc, char *argv[])\fP" 1c
Update documentation  
.IP "\fBMember \fBexceptions::FailedToOpenFileException::FailedToOpenFileException\fP (const std::string &file)\fP" 1c
Documentation  
.IP "\fBMember \fBexceptions::NoSuchDirException::NoSuchDirException\fP (const std::string &dir)\fP" 1c
Documentation  
.IP "\fBMember \fBmain\fP (int argc, char *argv[])\fP" 1c
Documentation 
.PP
.PP
Refactoring  
.IP "\fBpage \fBMain Page\fP \fP" 1c
Update \fBREADME\&.md\fP 
.IP "\fBMember \fBparsing::KeyValidator::getUnknownKeyLine\fP (const std::string &filename, const std::string &wrongKey)\fP" 1c
Documentation  
.IP "\fBMember \fBparsing::KeyValidator::validateEntries\fP (const std::string &filename, const std::vector< std::string > &entryKeys)\fP" 1c
Documentation  
.IP "\fBMember \fButilities::Utils::checkDirectory\fP (std::string &directory)\fP" 1c
documentation 
.PP

