.TH "src/sources/Utils.cpp" 3 "Sat Apr 27 2024 12:52:46" "Version 0.3.0" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sources/Utils.cpp \- Implementation for the Utils class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Utils\&.hpp'\fP
.br
\fC#include 'CommandLineHandler\&.hpp'\fP
.br
\fC#include 'Exceptions\&.hpp'\fP
.br
\fC#include 'config\&.hpp'\fP
.br
\fC#include <LoggingWrapper\&.hpp>\fP
.br
\fC#include <filesystem>\fP
.br
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fButilities\fP"
.br
.RI "Includes all utilities\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implementation for the Utils class\&. 


.PP
\fBAuthor\fP
.RS 4
Simon Blum 
.RE
.PP
\fBDate\fP
.RS 4
2024-04-26 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.2\&.2
.RE
.PP
This file includes the implementation for the Utils class\&.
.PP
\fBSee also\fP
.RS 4
src/include/utility/Utilities\&.hpp
.RE
.PP
\fBCopyright\fP
.RS 4
See LICENSE file 
.RE
.PP

.PP
Definition in file \fBUtils\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
