.TH "utilities" 3 "Fri Apr 26 2024 14:32:10" "Version 0.2.3" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utilities \- Includes all utilities\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUtils\fP"
.br
.RI "Responsible for utility function\&. "
.in -1c
.SH "Detailed Description"
.PP 
Includes all utilities\&. 

This namespace includes the \fBUtils\fP class with utility functions which can be used throughout the project\&.
.PP
\fBSee also\fP
.RS 4
\fBUtils\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
