.TH "src/include/Utils.hpp" 3 "Thu Apr 25 2024 19:29:40" "Version 0.2.1" "JSON2Batch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/Utils.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Exceptions\&.hpp'\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fButilities::Utils\fP"
.br
.RI "Responsible for utility function\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fButilities\fP"
.br
.RI "Includes all utilities\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for JSON2Batch from the source code\&.
