jsonToBatProject: el::base::TypedConfigurations Class Reference
el::base::TypedConfigurations Class Reference
Configurations with data types.
#include <easylogging++.h>
Public Member Functions
TypedConfigurations (Configurations *configurations, LogStreamsReferenceMapPtr logStreamsReference)
Constructor to initialize (construct) the object off el::Configurations.
TypedConfigurations (const TypedConfigurations &other)
virtual ~TypedConfigurations (void)
const Configurations * configurations (void) const
bool enabled (Level level)
bool toFile (Level level)
const std::string & filename (Level level)
bool toStandardOutput (Level level)
const base::LogFormat & logFormat (Level level)
const base::SubsecondPrecision & subsecondPrecision (Level level=Level::Global)
const base::MillisecondsWidth & millisecondsWidth (Level level=Level::Global)
bool performanceTracking (Level level=Level::Global)
base::type::fstream_t * fileStream (Level level)
std::size_t maxLogFileSize (Level level)
std::size_t logFlushThreshold (Level level)
Public Member Functions inherited from el::base::threading::ThreadSafe
virtual void acquireLock (void) ELPP_FINAL
virtual void releaseLock (void) ELPP_FINAL
virtual base::threading::Mutex & lock (void) ELPP_FINAL
Private Member Functions
template<typename Conf_T >
Conf_T getConfigByVal (Level level, const std::unordered_map< Level, Conf_T > *confMap, const char *confName)
template<typename Conf_T >
Conf_T & getConfigByRef (Level level, std::unordered_map< Level, Conf_T > *confMap, const char *confName)
template<typename Conf_T >
Conf_T unsafeGetConfigByVal (Level level, const std::unordered_map< Level, Conf_T > *confMap, const char *confName)
template<typename Conf_T >
Conf_T & unsafeGetConfigByRef (Level level, std::unordered_map< Level, Conf_T > *confMap, const char *confName)
template<typename Conf_T >
void setValue (Level level, const Conf_T &value, std::unordered_map< Level, Conf_T > *confMap, bool includeGlobalLevel=true)
void build (Configurations *configurations)
unsigned long getULong (std::string confVal)
std::string resolveFilename (const std::string &filename)
void insertFile (Level level, const std::string &fullFilename)
bool unsafeValidateFileRolling (Level level, const PreRollOutCallback &preRollOutCallback)
bool validateFileRolling (Level level, const PreRollOutCallback &preRollOutCallback)
Private Attributes
Configurations * m_configurations
std::unordered_map< Level, bool > m_enabledMap
std::unordered_map< Level, bool > m_toFileMap
std::unordered_map< Level, std::string > m_filenameMap
std::unordered_map< Level, bool > m_toStandardOutputMap
std::unordered_map< Level, base::LogFormat > m_logFormatMap
std::unordered_map< Level, base::SubsecondPrecision > m_subsecondPrecisionMap
std::unordered_map< Level, bool > m_performanceTrackingMap
std::unordered_map< Level, base::FileStreamPtr > m_fileStreamMap
std::unordered_map< Level, std::size_t > m_maxLogFileSizeMap
std::unordered_map< Level, std::size_t > m_logFlushThresholdMap
LogStreamsReferenceMapPtr m_logStreamsReference = nullptr
Friends
class el::Helpers
class el::base::MessageBuilder
class el::base::Writer
class el::base::DefaultLogDispatchCallback
class el::base::LogDispatcher
Additional Inherited Members
Protected Member Functions inherited from el::base::threading::ThreadSafe
ThreadSafe (void)
virtual ~ThreadSafe (void)
Detailed Description
Configurations with data types.
@detail el::Configurations have string based values. This is whats used internally in order to read correct configurations. This is to perform faster while writing logs using correct configurations.
This is thread safe and final class containing non-virtual destructor (means nothing should inherit this class)
Definition at line 1904 of file easylogging++.h.
Constructor & Destructor Documentation
TypedConfigurations() [1/2]
el::base::TypedConfigurations::TypedConfigurations (Configurations * configurations, LogStreamsReferenceMapPtr logStreamsReference)
Constructor to initialize (construct) the object off el::Configurations.
Parameters
configurations Configurations pointer/reference to base this typed configurations off.
logStreamsReference Use ELPP->registeredLoggers()->logStreamsReference()
Definition at line 1613 of file easylogging++.cc.
References build(), and m_configurations.
TypedConfigurations() [2/2]
el::base::TypedConfigurations::TypedConfigurations (const TypedConfigurations & other)
Definition at line 1620 of file easylogging++.cc.
References build(), and m_configurations.
~TypedConfigurations()
virtual el::base::TypedConfigurations::~TypedConfigurations (void) inline virtual
Definition at line 1913 of file easylogging++.h.
Member Function Documentation
build()
void el::base::TypedConfigurations::build (Configurations * configurations) private
Definition at line 1670 of file easylogging++.cc.
References el::Configuration::configurationType(), el::base::defaultPreRollOutCallback(), el::Enabled, el::Filename, el::Format, getULong(), insertFile(), el::Configuration::level(), el::LogFlushThreshold, el::MaxLogFileSize, el::PerformanceTracking, el::SubsecondPrecision, el::ToFile, el::ToStandardOutput, el::base::utils::Str::trim(), unsafeValidateFileRolling(), and el::Configuration::value().
configurations()
const Configurations * el::base::TypedConfigurations::configurations (void) const inline
Definition at line 1916 of file easylogging++.h.
References m_configurations.
enabled()
bool el::base::TypedConfigurations::enabled (Level level)
Definition at line 1626 of file easylogging++.cc.
filename()
const std::string & el::base::TypedConfigurations::filename (Level level)
Definition at line 1634 of file easylogging++.cc.
fileStream()
base::type::fstream_t * el::base::TypedConfigurations::fileStream (Level level)
Definition at line 1658 of file easylogging++.cc.
getConfigByRef()
template<typename Conf_T > Conf_T & el::base::TypedConfigurations::getConfigByRef (Level level, std::unordered_map< Level, Conf_T > * confMap, const char * confName) inline private
Definition at line 1959 of file easylogging++.h.
getConfigByVal()
template<typename Conf_T > Conf_T el::base::TypedConfigurations::getConfigByVal (Level level, const std::unordered_map< Level, Conf_T > * confMap, const char * confName) inline private
Definition at line 1953 of file easylogging++.h.
getULong()
unsigned long el::base::TypedConfigurations::getULong (std::string confVal) private
Definition at line 1724 of file easylogging++.cc.
References el::base::utils::Str::isDigit(), and el::base::utils::Str::trim().
insertFile()
void el::base::TypedConfigurations::insertFile (Level level, const std::string & fullFilename) private
Definition at line 1778 of file easylogging++.cc.
References el::LevelHelper::convertToString(), el::base::utils::File::createPath(), el::base::utils::File::extractPathFromFilename(), el::base::consts::kFilePathSeparator, el::base::utils::File::newFileStream(), and resolveFilename().
logFlushThreshold()
std::size_t el::base::TypedConfigurations::logFlushThreshold (Level level)
Definition at line 1666 of file easylogging++.cc.
logFormat()
const base::LogFormat & el::base::TypedConfigurations::logFormat (Level level)
Definition at line 1642 of file easylogging++.cc.
maxLogFileSize()
std::size_t el::base::TypedConfigurations::maxLogFileSize (Level level)
Definition at line 1662 of file easylogging++.cc.
millisecondsWidth()
const base::MillisecondsWidth & el::base::TypedConfigurations::millisecondsWidth (Level level = Level::Global)
Definition at line 1650 of file easylogging++.cc.
performanceTracking()
bool el::base::TypedConfigurations::performanceTracking (Level level = Level::Global)
Definition at line 1654 of file easylogging++.cc.
resolveFilename()
std::string el::base::TypedConfigurations::resolveFilename (const std::string & filename) private
Definition at line 1739 of file easylogging++.cc.
References el::base::utils::DateTime::getDateTime(), el::base::consts::kDateTimeFormatSpecifierForFilename, el::base::consts::kDefaultDateTimeFormatInFilename, el::base::utils::Str::replaceAll(), el::base::utils::Str::replaceAll(), and el::base::SubsecondPrecision::SubsecondPrecision().
setValue()
template<typename Conf_T > void el::base::TypedConfigurations::setValue (Level level, const Conf_T & value, std::unordered_map< Level, Conf_T > * confMap, bool includeGlobalLevel = true) inline private
Definition at line 1998 of file easylogging++.h.
subsecondPrecision()
const base::SubsecondPrecision & el::base::TypedConfigurations::subsecondPrecision (Level level = Level::Global)
Definition at line 1646 of file easylogging++.cc.
toFile()
bool el::base::TypedConfigurations::toFile (Level level)
Definition at line 1630 of file easylogging++.cc.
toStandardOutput()
bool el::base::TypedConfigurations::toStandardOutput (Level level)
Definition at line 1638 of file easylogging++.cc.
unsafeGetConfigByRef()
template<typename Conf_T > Conf_T & el::base::TypedConfigurations::unsafeGetConfigByRef (Level level, std::unordered_map< Level, Conf_T > * confMap, const char * confName) inline private
Definition at line 1982 of file easylogging++.h.
References el::Global.
unsafeGetConfigByVal()
template<typename Conf_T > Conf_T el::base::TypedConfigurations::unsafeGetConfigByVal (Level level, const std::unordered_map< Level, Conf_T > * confMap, const char * confName) inline private
Definition at line 1965 of file easylogging++.h.
References el::Global.
unsafeValidateFileRolling()
bool el::base::TypedConfigurations::unsafeValidateFileRolling (Level level, const PreRollOutCallback & preRollOutCallback) private
Definition at line 1815 of file easylogging++.cc.
References el::base::utils::File::getSizeOfFile().
validateFileRolling()
bool el::base::TypedConfigurations::validateFileRolling (Level level, const PreRollOutCallback & preRollOutCallback) inline private
Definition at line 2027 of file easylogging++.h.
References unsafeValidateFileRolling().
Friends And Related Symbol Documentation
el::base::DefaultLogDispatchCallback
friend class el::base::DefaultLogDispatchCallback friend
Definition at line 1949 of file easylogging++.h.
el::base::LogDispatcher
friend class el::base::LogDispatcher friend
Definition at line 1950 of file easylogging++.h.
el::base::MessageBuilder
friend class el::base::MessageBuilder friend
Definition at line 1947 of file easylogging++.h.
el::base::Writer
friend class el::base::Writer friend
Definition at line 1948 of file easylogging++.h.
el::Helpers
friend class el::Helpers friend
Definition at line 1946 of file easylogging++.h.
Field Documentation
m_configurations
Configurations* el::base::TypedConfigurations::m_configurations private
Definition at line 1933 of file easylogging++.h.
m_enabledMap
std::unordered_map<Level, bool> el::base::TypedConfigurations::m_enabledMap private
Definition at line 1934 of file easylogging++.h.
m_filenameMap
std::unordered_map<Level, std::string> el::base::TypedConfigurations::m_filenameMap private
Definition at line 1936 of file easylogging++.h.
m_fileStreamMap
std::unordered_map<Level, base::FileStreamPtr> el::base::TypedConfigurations::m_fileStreamMap private
Definition at line 1941 of file easylogging++.h.
m_logFlushThresholdMap
std::unordered_map<Level, std::size_t> el::base::TypedConfigurations::m_logFlushThresholdMap private
Definition at line 1943 of file easylogging++.h.
m_logFormatMap
std::unordered_map<Level, base::LogFormat> el::base::TypedConfigurations::m_logFormatMap private
Definition at line 1938 of file easylogging++.h.
m_logStreamsReference
LogStreamsReferenceMapPtr el::base::TypedConfigurations::m_logStreamsReference = nullptr private
Definition at line 1944 of file easylogging++.h.
m_maxLogFileSizeMap
std::unordered_map<Level, std::size_t> el::base::TypedConfigurations::m_maxLogFileSizeMap private
Definition at line 1942 of file easylogging++.h.
m_performanceTrackingMap
std::unordered_map<Level, bool> el::base::TypedConfigurations::m_performanceTrackingMap private
Definition at line 1940 of file easylogging++.h.
m_subsecondPrecisionMap
std::unordered_map<Level, base::SubsecondPrecision> el::base::TypedConfigurations::m_subsecondPrecisionMap private
Definition at line 1939 of file easylogging++.h.
m_toFileMap
std::unordered_map<Level, bool> el::base::TypedConfigurations::m_toFileMap private
Definition at line 1935 of file easylogging++.h.
m_toStandardOutputMap
std::unordered_map<Level, bool> el::base::TypedConfigurations::m_toStandardOutputMap private
Definition at line 1937 of file easylogging++.h.
The documentation for this class was generated from the following files:
lib/easylogging++.h
lib/easylogging++.cc