jsonToBatProject: el::Logger Class Reference
el::Logger Class Reference
Represents a logger holding ID and configurations we need to write logs.
#include <easylogging++.h>
Public Member Functions
Logger (const std::string &id, base::LogStreamsReferenceMapPtr logStreamsReference)
Logger (const std::string &id, const Configurations &configurations, base::LogStreamsReferenceMapPtr logStreamsReference)
Logger (const Logger &logger)
Logger & operator= (const Logger &logger)
virtual ~Logger (void)
virtual void log (el::base::type::ostream_t &os) const
void configure (const Configurations &configurations)
Configures the logger using specified configurations.
void reconfigure (void)
Reconfigures logger using existing configurations.
const std::string & id (void) const
const std::string & parentApplicationName (void) const
void setParentApplicationName (const std::string &parentApplicationName)
Configurations * configurations (void)
base::TypedConfigurations * typedConfigurations (void)
void flush (void)
Flushes logger to sync all log files for all levels.
void flush (Level level, base::type::fstream_t *fs)
bool isFlushNeeded (Level level)
LogBuilder * logBuilder (void) const
void setLogBuilder (const LogBuilderPtr &logBuilder)
bool enabled (Level level) const
Public Member Functions inherited from el::base::threading::ThreadSafe
virtual void acquireLock (void) ELPP_FINAL
virtual void releaseLock (void) ELPP_FINAL
virtual base::threading::Mutex & lock (void) ELPP_FINAL
Public Member Functions inherited from el::Loggable
virtual ~Loggable (void)
Static Public Member Functions
static bool isValidId (const std::string &id)
Private Member Functions
Logger (void)
void initUnflushedCount (void)
base::type::stringstream_t & stream (void)
void resolveLoggerFormatSpec (void) const
Private Attributes
std::string m_id
base::TypedConfigurations * m_typedConfigurations
base::type::stringstream_t m_stream
std::string m_parentApplicationName
bool m_isConfigured
Configurations m_configurations
std::unordered_map< Level, unsigned int > m_unflushedCount
base::LogStreamsReferenceMapPtr m_logStreamsReference = nullptr
LogBuilderPtr m_logBuilder
Friends
class el::LogMessage
class el::Loggers
class el::Helpers
class el::base::RegisteredLoggers
class el::base::DefaultLogDispatchCallback
class el::base::MessageBuilder
class el::base::Writer
class el::base::PErrorWriter
class el::base::Storage
class el::base::PerformanceTracker
class el::base::LogDispatcher
Additional Inherited Members
Protected Member Functions inherited from el::base::threading::ThreadSafe
ThreadSafe (void)
virtual ~ThreadSafe (void)
Detailed Description
Represents a logger holding ID and configurations we need to write logs.
@detail This class does not write logs itself instead its used by writer to read configurations from.
Definition at line 2213 of file easylogging++.h.
Constructor & Destructor Documentation
Logger() [1/4]
el::Logger::Logger (const std::string & id, base::LogStreamsReferenceMapPtr logStreamsReference)
Definition at line 598 of file easylogging++.cc.
References initUnflushedCount(), Logger(), m_id, m_isConfigured, m_parentApplicationName, and m_typedConfigurations.
Logger() [2/4]
el::Logger::Logger (const std::string & id, const Configurations & configurations, base::LogStreamsReferenceMapPtr logStreamsReference)
Definition at line 607 of file easylogging++.cc.
References configure(), initUnflushedCount(), Logger(), m_id, m_isConfigured, m_parentApplicationName, and m_typedConfigurations.
Logger() [3/4]
el::Logger::Logger (const Logger & logger)
Definition at line 618 of file easylogging++.cc.
References m_id, m_isConfigured, m_parentApplicationName, and m_typedConfigurations.
~Logger()
virtual el::Logger::~Logger (void) inline virtual
Definition at line 2220 of file easylogging++.h.
References m_typedConfigurations.
Logger() [4/4]
el::Logger::Logger (void) private
Member Function Documentation
configurations()
Configurations * el::Logger::configurations (void) inline
Definition at line 2246 of file easylogging++.h.
configure()
void el::Logger::configure (const Configurations & configurations)
Configures the logger using specified configurations.
Definition at line 643 of file easylogging++.cc.
References el::base::TypedConfigurations::configurations(), el::Filename, flush(), el::Global, el::Configurations::hasConfiguration(), initUnflushedCount(), m_isConfigured, m_typedConfigurations, and resolveLoggerFormatSpec().
enabled()
bool el::Logger::enabled (Level level) const inline
Definition at line 2273 of file easylogging++.h.
References el::base::TypedConfigurations::enabled(), and m_typedConfigurations.
flush() [1/2]
void el::Logger::flush (Level level, base::type::fstream_t * fs)
Definition at line 686 of file easylogging++.cc.
References el::base::TypedConfigurations::fileStream(), m_typedConfigurations, el::base::TypedConfigurations::toFile(), and el::Helpers::validateFileRolling().
flush() [2/2]
void el::Logger::flush (void)
Flushes logger to sync all log files for all levels.
Definition at line 676 of file easylogging++.cc.
References el::LevelHelper::castFromInt(), flush(), el::LevelHelper::forEachLevel(), and el::LevelHelper::kMinValid.
id()
const std::string & el::Logger::id (void) const inline
Definition at line 2234 of file easylogging++.h.
References m_id.
initUnflushedCount()
void el::Logger::initUnflushedCount (void) private
Definition at line 700 of file easylogging++.cc.
References el::LevelHelper::forEachLevel(), and el::LevelHelper::kMinValid.
isFlushNeeded()
bool el::Logger::isFlushNeeded (Level level) inline
Definition at line 2261 of file easylogging++.h.
isValidId()
bool el::Logger::isValidId (const std::string & id) static
Definition at line 667 of file easylogging++.cc.
References el::base::utils::Str::contains(), and el::base::consts::kValidLoggerIdSymbols.
log()
virtual void el::Logger::log (el::base::type::ostream_t & os) const inline virtual
Implements el::Loggable.
Definition at line 2224 of file easylogging++.h.
References m_id.
logBuilder()
LogBuilder * el::Logger::logBuilder (void) const inline
Definition at line 2265 of file easylogging++.h.
operator=()
Logger & el::Logger::operator= (const Logger & logger)
Definition at line 629 of file easylogging++.cc.
References m_id, m_isConfigured, m_parentApplicationName, and m_typedConfigurations.
parentApplicationName()
const std::string & el::Logger::parentApplicationName (void) const inline
Definition at line 2238 of file easylogging++.h.
References m_parentApplicationName.
reconfigure()
void el::Logger::reconfigure (void)
Reconfigures logger using existing configurations.
Definition at line 662 of file easylogging++.cc.
resolveLoggerFormatSpec()
void el::Logger::resolveLoggerFormatSpec (void) const private
Definition at line 709 of file easylogging++.cc.
References el::LevelHelper::castFromInt(), el::LevelHelper::forEachLevel(), el::base::consts::kLoggerIdFormatSpecifier, el::LevelHelper::kMinValid, el::base::TypedConfigurations::logFormat(), el::base::LogFormat::m_format, m_id, m_typedConfigurations, and el::base::utils::Str::replaceFirstWithEscape().
setLogBuilder()
void el::Logger::setLogBuilder (const LogBuilderPtr & logBuilder) inline
Definition at line 2269 of file easylogging++.h.
setParentApplicationName()
void el::Logger::setParentApplicationName (const std::string & parentApplicationName) inline
Definition at line 2242 of file easylogging++.h.
References m_parentApplicationName.
stream()
base::type::stringstream_t & el::Logger::stream (void) inline private
Definition at line 2339 of file easylogging++.h.
References m_stream.
typedConfigurations()
base::TypedConfigurations * el::Logger::typedConfigurations (void) inline
Definition at line 2250 of file easylogging++.h.
References m_typedConfigurations.
Friends And Related Symbol Documentation
el::base::DefaultLogDispatchCallback
friend class el::base::DefaultLogDispatchCallback friend
Definition at line 2313 of file easylogging++.h.
el::base::LogDispatcher
friend class el::base::LogDispatcher friend
Definition at line 2319 of file easylogging++.h.
el::base::MessageBuilder
friend class el::base::MessageBuilder friend
Definition at line 2314 of file easylogging++.h.
el::base::PerformanceTracker
friend class el::base::PerformanceTracker friend
Definition at line 2318 of file easylogging++.h.
el::base::PErrorWriter
friend class el::base::PErrorWriter friend
Definition at line 2316 of file easylogging++.h.
el::base::RegisteredLoggers
friend class el::base::RegisteredLoggers friend
Definition at line 2312 of file easylogging++.h.
el::base::Storage
friend class el::base::Storage friend
Definition at line 2317 of file easylogging++.h.
el::base::Writer
friend class el::base::Writer friend
Definition at line 2315 of file easylogging++.h.
el::Helpers
friend class el::Helpers friend
Definition at line 2311 of file easylogging++.h.
el::Loggers
friend class el::Loggers friend
Definition at line 2310 of file easylogging++.h.
el::LogMessage
friend class el::LogMessage friend
Definition at line 2309 of file easylogging++.h.
Field Documentation
m_configurations
Configurations el::Logger::m_configurations private
Definition at line 2304 of file easylogging++.h.
m_id
std::string el::Logger::m_id private
Definition at line 2299 of file easylogging++.h.
m_isConfigured
bool el::Logger::m_isConfigured private
Definition at line 2303 of file easylogging++.h.
m_logBuilder
LogBuilderPtr el::Logger::m_logBuilder private
Definition at line 2307 of file easylogging++.h.
m_logStreamsReference
base::LogStreamsReferenceMapPtr el::Logger::m_logStreamsReference = nullptr private
Definition at line 2306 of file easylogging++.h.
m_parentApplicationName
std::string el::Logger::m_parentApplicationName private
Definition at line 2302 of file easylogging++.h.
m_stream
base::type::stringstream_t el::Logger::m_stream private
Definition at line 2301 of file easylogging++.h.
m_typedConfigurations
base::TypedConfigurations* el::Logger::m_typedConfigurations private
Definition at line 2300 of file easylogging++.h.
m_unflushedCount
std::unordered_map<Level, unsigned int> el::Logger::m_unflushedCount private
Definition at line 2305 of file easylogging++.h.
The documentation for this class was generated from the following files:
lib/easylogging++.h
lib/easylogging++.cc