jsonToBatProject: el::base::RegisteredHitCounters Class Reference
el::base::RegisteredHitCounters Class Reference
Repository for hit counters used across the application.
#include <easylogging++.h>
Public Member Functions
bool validateEveryN (const char *filename, base::type::LineNumber lineNumber, std::size_t n)
Validates counter for every N, i.e, registers new if does not exist otherwise updates original one.
bool validateAfterN (const char *filename, base::type::LineNumber lineNumber, std::size_t n)
Validates counter for hits >= N, i.e, registers new if does not exist otherwise updates original one.
bool validateNTimes (const char *filename, base::type::LineNumber lineNumber, std::size_t n)
Validates counter for hits are <= n, i.e, registers new if does not exist otherwise updates original one.
const base::HitCounter * getCounter (const char *filename, base::type::LineNumber lineNumber)
Gets hit counter registered at specified position.
Public Member Functions inherited from el::base::utils::RegistryWithPred< base::HitCounter, base::HitCounter::Predicate >
RegistryWithPred (void)
RegistryWithPred (const RegistryWithPred &sr)
Copy constructor that is useful for base classes. Try to avoid this constructor, use move constructor.
virtual ~RegistryWithPred (void)
RegistryWithPred & operator= (const RegistryWithPred &sr)
Assignment operator that unregisters all the existing registries and deeply copies each of repo element.
Public Member Functions inherited from el::base::utils::AbstractRegistry< T_Ptr, Container >
AbstractRegistry (void)
Default constructor.
AbstractRegistry (AbstractRegistry &&sr)
Move constructor that is useful for base classes.
bool operator== (const AbstractRegistry< T_Ptr, Container > &other)
bool operator!= (const AbstractRegistry< T_Ptr, Container > &other)
AbstractRegistry & operator= (AbstractRegistry &&sr)
Assignment move operator.
virtual ~AbstractRegistry (void)
virtual iterator begin (void) ELPP_FINAL
virtual iterator end (void) ELPP_FINAL
virtual const_iterator cbegin (void) const ELPP_FINAL
virtual const_iterator cend (void) const ELPP_FINAL
virtual bool empty (void) const ELPP_FINAL
virtual std::size_t size (void) const ELPP_FINAL
virtual Container & list (void) ELPP_FINAL
Returns underlying container by reference.
virtual const Container & list (void) const ELPP_FINAL
Returns underlying container by constant reference.
Public Member Functions inherited from el::base::threading::ThreadSafe
virtual void acquireLock (void) ELPP_FINAL
virtual void releaseLock (void) ELPP_FINAL
virtual base::threading::Mutex & lock (void) ELPP_FINAL
Additional Inherited Members
Public Types inherited from el::base::utils::RegistryWithPred< base::HitCounter, base::HitCounter::Predicate >
typedef RegistryWithPred< base::HitCounter, base::HitCounter::Predicate >::iterator iterator
typedef RegistryWithPred< base::HitCounter, base::HitCounter::Predicate >::const_iterator const_iterator
Public Types inherited from el::base::utils::AbstractRegistry< T_Ptr, Container >
typedef Container::iterator iterator
typedef Container::const_iterator const_iterator
Protected Member Functions inherited from el::base::utils::RegistryWithPred< base::HitCounter, base::HitCounter::Predicate >
virtual void unregisterAll (void) ELPP_FINAL
Unregisters all the pointers from current repository.
virtual void unregister (base::HitCounter *&ptr) ELPP_FINAL
virtual void registerNew (base::HitCounter *ptr) ELPP_FINAL
base::HitCounter * get (const T &arg1, const T2 arg2)
Gets pointer from repository with specified arguments. Arguments are passed to predicate in order to validate pointer.
Protected Member Functions inherited from el::base::utils::AbstractRegistry< T_Ptr, Container >
virtual void deepCopy (const AbstractRegistry< T_Ptr, Container > &)=0
void reinitDeepCopy (const AbstractRegistry< T_Ptr, Container > &sr)
Protected Member Functions inherited from el::base::threading::ThreadSafe
ThreadSafe (void)
virtual ~ThreadSafe (void)
Detailed Description
Repository for hit counters used across the application.
Definition at line 2118 of file easylogging++.h.
Member Function Documentation
getCounter()
const base::HitCounter * el::base::RegisteredHitCounters::getCounter (const char * filename, base::type::LineNumber lineNumber) inline
Gets hit counter registered at specified position.
Definition at line 2133 of file easylogging++.h.
validateAfterN()
bool el::base::RegisteredHitCounters::validateAfterN (const char * filename, base::type::LineNumber lineNumber, std::size_t n)
Validates counter for hits >= N, i.e, registers new if does not exist otherwise updates original one.
Returns
True if validation resulted in triggering hit. Meaning logs should be written everytime true is returned
Definition at line 1849 of file easylogging++.cc.
References el::base::HitCounter::HitCounter(), el::base::HitCounter::hitCounts(), and el::base::HitCounter::increment().
validateEveryN()
bool el::base::RegisteredHitCounters::validateEveryN (const char * filename, base::type::LineNumber lineNumber, std::size_t n)
Validates counter for every N, i.e, registers new if does not exist otherwise updates original one.
Returns
True if validation resulted in triggering hit. Meaning logs should be written everytime true is returned
Definition at line 1836 of file easylogging++.cc.
References el::base::HitCounter::HitCounter(), el::base::HitCounter::hitCounts(), and el::base::HitCounter::validateHitCounts().
validateNTimes()
bool el::base::RegisteredHitCounters::validateNTimes (const char * filename, base::type::LineNumber lineNumber, std::size_t n)
Validates counter for hits are <= n, i.e, registers new if does not exist otherwise updates original one.
Returns
True if validation resulted in triggering hit. Meaning logs should be written everytime true is returned
Definition at line 1866 of file easylogging++.cc.
References el::base::HitCounter::HitCounter(), el::base::HitCounter::hitCounts(), and el::base::HitCounter::increment().
The documentation for this class was generated from the following files:
lib/easylogging++.h
lib/easylogging++.cc