jsonToBatProject: el::base::Storage Class Reference
el::base::Storage Class Reference
Easylogging++ management storage.
#include <easylogging++.h>
Public Member Functions
Storage (const LogBuilderPtr &defaultLogBuilder)
virtual ~Storage (void)
bool validateEveryNCounter (const char *filename, base::type::LineNumber lineNumber, std::size_t occasion)
bool validateAfterNCounter (const char *filename, base::type::LineNumber lineNumber, std::size_t n)
bool validateNTimesCounter (const char *filename, base::type::LineNumber lineNumber, std::size_t n)
base::RegisteredHitCounters * hitCounters (void) const
base::RegisteredLoggers * registeredLoggers (void) const
base::VRegistry * vRegistry (void) const
const base::utils::CommandLineArgs * commandLineArgs (void) const
void addFlag (LoggingFlag flag)
void removeFlag (LoggingFlag flag)
bool hasFlag (LoggingFlag flag) const
base::type::EnumType flags (void) const
void setFlags (base::type::EnumType flags)
void setPreRollOutCallback (const PreRollOutCallback &callback)
void unsetPreRollOutCallback (void)
PreRollOutCallback & preRollOutCallback (void)
bool hasCustomFormatSpecifier (const char *formatSpecifier)
void installCustomFormatSpecifier (const CustomFormatSpecifier &customFormatSpecifier)
bool uninstallCustomFormatSpecifier (const char *formatSpecifier)
const std::vector< CustomFormatSpecifier > * customFormatSpecifiers (void) const
base::threading::Mutex & customFormatSpecifiersLock ()
void setLoggingLevel (Level level)
template<typename T >
bool installLogDispatchCallback (const std::string &id)
template<typename T >
void uninstallLogDispatchCallback (const std::string &id)
template<typename T >
T * logDispatchCallback (const std::string &id)
void setThreadName (const std::string &name)
Sets thread name for current thread. Requires std::thread.
std::string getThreadName (const std::string &threadId)
Public Member Functions inherited from el::base::threading::ThreadSafe
virtual void acquireLock (void) ELPP_FINAL
virtual void releaseLock (void) ELPP_FINAL
virtual base::threading::Mutex & lock (void) ELPP_FINAL
Private Member Functions
void setApplicationArguments (int argc, char **argv)
void setApplicationArguments (int argc, const char **argv)
Private Member Functions inherited from el::base::NoCopy
NoCopy (void)
Private Attributes
base::RegisteredHitCounters * m_registeredHitCounters
base::RegisteredLoggers * m_registeredLoggers
base::type::EnumType m_flags
base::VRegistry * m_vRegistry
base::utils::CommandLineArgs m_commandLineArgs
PreRollOutCallback m_preRollOutCallback
std::unordered_map< std::string, base::type::LogDispatchCallbackPtr > m_logDispatchCallbacks
std::unordered_map< std::string, base::type::PerformanceTrackingCallbackPtr > m_performanceTrackingCallbacks
std::unordered_map< std::string, std::string > m_threadNames
std::vector< CustomFormatSpecifier > m_customFormatSpecifiers
base::threading::Mutex m_customFormatSpecifiersLock
base::threading::Mutex m_threadNamesLock
Level m_loggingLevel
Friends
class el::Helpers
class el::base::DefaultLogDispatchCallback
class el::LogBuilder
class el::base::MessageBuilder
class el::base::Writer
class el::base::PerformanceTracker
class el::base::LogDispatcher
Additional Inherited Members
Protected Member Functions inherited from el::base::threading::ThreadSafe
ThreadSafe (void)
virtual ~ThreadSafe (void)
Detailed Description
Easylogging++ management storage.
Definition at line 2551 of file easylogging++.h.
Constructor & Destructor Documentation
Storage()
el::base::Storage::Storage (const LogBuilderPtr & defaultLogBuilder) explicit
Definition at line 2061 of file easylogging++.cc.
References addFlag(), el::AllowVerboseIfModuleNotSpecified, el::base::RegisteredLoggers::get(), el::base::consts::kDefaultLoggerId, m_flags, m_registeredHitCounters, m_registeredLoggers, m_vRegistry, el::base::RegisteredLoggers::RegisteredLoggers(), Storage(), and el::base::VRegistry::VRegistry().
~Storage()
el::base::Storage::~Storage (void) virtual
Definition at line 2109 of file easylogging++.cc.
References m_registeredHitCounters, m_registeredLoggers, and m_vRegistry.
Member Function Documentation
addFlag()
void el::base::Storage::addFlag (LoggingFlag flag) inline
Definition at line 2595 of file easylogging++.h.
References m_flags.
commandLineArgs()
const base::utils::CommandLineArgs * el::base::Storage::commandLineArgs (void) const inline
Definition at line 2591 of file easylogging++.h.
customFormatSpecifiers()
const std::vector< CustomFormatSpecifier > * el::base::Storage::customFormatSpecifiers (void) const inline
Definition at line 2631 of file easylogging++.h.
customFormatSpecifiersLock()
base::threading::Mutex & el::base::Storage::customFormatSpecifiersLock () inline
Definition at line 2635 of file easylogging++.h.
References m_customFormatSpecifiersLock.
flags()
base::type::EnumType el::base::Storage::flags (void) const inline
Definition at line 2607 of file easylogging++.h.
References m_flags.
getThreadName()
std::string el::base::Storage::getThreadName (const std::string & threadId) inline
Definition at line 2683 of file easylogging++.h.
hasCustomFormatSpecifier()
bool el::base::Storage::hasCustomFormatSpecifier (const char * formatSpecifier)
Definition at line 2128 of file easylogging++.cc.
hasFlag()
bool el::base::Storage::hasFlag (LoggingFlag flag) const inline
Definition at line 2603 of file easylogging++.h.
References m_flags.
hitCounters()
base::RegisteredHitCounters * el::base::Storage::hitCounters (void) const inline
Definition at line 2573 of file easylogging++.h.
References m_registeredHitCounters.
installCustomFormatSpecifier()
void el::base::Storage::installCustomFormatSpecifier (const CustomFormatSpecifier & customFormatSpecifier)
Definition at line 2134 of file easylogging++.cc.
References el::CustomFormatSpecifier::formatSpecifier(), and hasCustomFormatSpecifier().
installLogDispatchCallback()
template<typename T > bool el::base::Storage::installLogDispatchCallback (const std::string & id) inline
Definition at line 2644 of file easylogging++.h.
logDispatchCallback()
template<typename T > T * el::base::Storage::logDispatchCallback (const std::string & id) inline
Definition at line 2653 of file easylogging++.h.
preRollOutCallback()
PreRollOutCallback & el::base::Storage::preRollOutCallback (void) inline
Definition at line 2623 of file easylogging++.h.
registeredLoggers()
base::RegisteredLoggers * el::base::Storage::registeredLoggers (void) const inline
Definition at line 2577 of file easylogging++.h.
References m_registeredLoggers.
removeFlag()
void el::base::Storage::removeFlag (LoggingFlag flag) inline
Definition at line 2599 of file easylogging++.h.
References m_flags.
setApplicationArguments() [1/2]
void el::base::Storage::setApplicationArguments (int argc, char ** argv) private
Definition at line 2153 of file easylogging++.cc.
References commandLineArgs(), m_vRegistry, registeredLoggers(), el::base::RegisteredLoggers::setDefaultConfigurations(), and el::base::VRegistry::setFromArgs().
setApplicationArguments() [2/2]
void el::base::Storage::setApplicationArguments (int argc, const char ** argv) inline private
Definition at line 2720 of file easylogging++.h.
References setApplicationArguments().
setFlags()
void el::base::Storage::setFlags (base::type::EnumType flags) inline
Definition at line 2611 of file easylogging++.h.
References m_flags.
setLoggingLevel()
void el::base::Storage::setLoggingLevel (Level level) inline
Definition at line 2639 of file easylogging++.h.
References m_loggingLevel.
setPreRollOutCallback()
void el::base::Storage::setPreRollOutCallback (const PreRollOutCallback & callback) inline
Definition at line 2615 of file easylogging++.h.
setThreadName()
void el::base::Storage::setThreadName (const std::string & name) inline
Sets thread name for current thread. Requires std::thread.
Definition at line 2677 of file easylogging++.h.
uninstallCustomFormatSpecifier()
bool el::base::Storage::uninstallCustomFormatSpecifier (const char * formatSpecifier)
Definition at line 2142 of file easylogging++.cc.
uninstallLogDispatchCallback()
template<typename T > void el::base::Storage::uninstallLogDispatchCallback (const std::string & id) inline
Definition at line 2649 of file easylogging++.h.
unsetPreRollOutCallback()
void el::base::Storage::unsetPreRollOutCallback (void) inline
Definition at line 2619 of file easylogging++.h.
validateAfterNCounter()
bool el::base::Storage::validateAfterNCounter (const char * filename, base::type::LineNumber lineNumber, std::size_t n) inline
Definition at line 2565 of file easylogging++.h.
References hitCounters(), and el::base::RegisteredHitCounters::validateAfterN().
validateEveryNCounter()
bool el::base::Storage::validateEveryNCounter (const char * filename, base::type::LineNumber lineNumber, std::size_t occasion) inline
Definition at line 2561 of file easylogging++.h.
References hitCounters(), and el::base::RegisteredHitCounters::validateEveryN().
validateNTimesCounter()
bool el::base::Storage::validateNTimesCounter (const char * filename, base::type::LineNumber lineNumber, std::size_t n) inline
Definition at line 2569 of file easylogging++.h.
References hitCounters(), and el::base::RegisteredHitCounters::validateNTimes().
vRegistry()
base::VRegistry * el::base::Storage::vRegistry (void) const inline
Definition at line 2581 of file easylogging++.h.
References m_vRegistry.
Friends And Related Symbol Documentation
el::base::DefaultLogDispatchCallback
friend class el::base::DefaultLogDispatchCallback friend
Definition at line 2711 of file easylogging++.h.
el::base::LogDispatcher
friend class el::base::LogDispatcher friend
Definition at line 2716 of file easylogging++.h.
el::base::MessageBuilder
friend class el::base::MessageBuilder friend
Definition at line 2713 of file easylogging++.h.
el::base::PerformanceTracker
friend class el::base::PerformanceTracker friend
Definition at line 2715 of file easylogging++.h.
el::base::Writer
friend class el::base::Writer friend
Definition at line 2714 of file easylogging++.h.
el::Helpers
friend class el::Helpers friend
Definition at line 2710 of file easylogging++.h.
el::LogBuilder
friend class el::LogBuilder friend
Definition at line 2712 of file easylogging++.h.
Field Documentation
m_commandLineArgs
base::utils::CommandLineArgs el::base::Storage::m_commandLineArgs private
Definition at line 2700 of file easylogging++.h.
m_customFormatSpecifiers
std::vector<CustomFormatSpecifier> el::base::Storage::m_customFormatSpecifiers private
Definition at line 2705 of file easylogging++.h.
m_customFormatSpecifiersLock
base::threading::Mutex el::base::Storage::m_customFormatSpecifiersLock private
Definition at line 2706 of file easylogging++.h.
m_flags
base::type::EnumType el::base::Storage::m_flags private
Definition at line 2694 of file easylogging++.h.
m_logDispatchCallbacks
std::unordered_map<std::string, base::type::LogDispatchCallbackPtr> el::base::Storage::m_logDispatchCallbacks private
Definition at line 2702 of file easylogging++.h.
m_loggingLevel
Level el::base::Storage::m_loggingLevel private
Definition at line 2708 of file easylogging++.h.
m_performanceTrackingCallbacks
std::unordered_map<std::string, base::type::PerformanceTrackingCallbackPtr> el::base::Storage::m_performanceTrackingCallbacks private
Definition at line 2703 of file easylogging++.h.
m_preRollOutCallback
PreRollOutCallback el::base::Storage::m_preRollOutCallback private
Definition at line 2701 of file easylogging++.h.
m_registeredHitCounters
base::RegisteredHitCounters* el::base::Storage::m_registeredHitCounters private
Definition at line 2692 of file easylogging++.h.
m_registeredLoggers
base::RegisteredLoggers* el::base::Storage::m_registeredLoggers private
Definition at line 2693 of file easylogging++.h.
m_threadNames
std::unordered_map<std::string, std::string> el::base::Storage::m_threadNames private
Definition at line 2704 of file easylogging++.h.
m_threadNamesLock
base::threading::Mutex el::base::Storage::m_threadNamesLock private
Definition at line 2707 of file easylogging++.h.
m_vRegistry
base::VRegistry* el::base::Storage::m_vRegistry private
Definition at line 2695 of file easylogging++.h.
The documentation for this class was generated from the following files:
lib/easylogging++.h
lib/easylogging++.cc