jsonToBatProject: el::base::MessageBuilder Class Reference
el::base::MessageBuilder Class Reference
#include <easylogging++.h>
Public Member Functions
MessageBuilder (void)
void initialize (Logger *logger)
MessageBuilder & operator<< (const std::string &msg)
MessageBuilder & operator<< (const std::wstring &msg)
MessageBuilder & operator<< (const wchar_t *msg)
MessageBuilder & operator<< (std::ostream &(*OStreamMani)(std::ostream &))
Private Member Functions
template<class Iterator >
MessageBuilder & writeIterator (Iterator begin_, Iterator end_, std::size_t size_)
Private Attributes
template<class Class >
Logger * m_logger
const base::type::char_t * m_containerLogSeparator
Detailed Description
Definition at line 2862 of file easylogging++.h.
Constructor & Destructor Documentation
MessageBuilder()
el::base::MessageBuilder::MessageBuilder (void) inline
Definition at line 2864 of file easylogging++.h.
References m_containerLogSeparator, and m_logger.
Member Function Documentation
initialize()
void el::base::MessageBuilder::initialize (Logger * logger)
Definition at line 2505 of file easylogging++.cc.
References m_logger.
operator<<() [1/4]
MessageBuilder & el::base::MessageBuilder::operator<< (const std::string & msg) inline
Definition at line 2876 of file easylogging++.h.
operator<<() [2/4]
MessageBuilder & el::base::MessageBuilder::operator<< (const std::wstring & msg) inline
Definition at line 2893 of file easylogging++.h.
operator<<() [3/4]
MessageBuilder & el::base::MessageBuilder::operator<< (const wchar_t * msg)
Definition at line 2511 of file easylogging++.cc.
References el::base::consts::kNullPointer, m_logger, el::Logger::stream(), and el::base::utils::Str::wcharPtrToCharPtr().
operator<<() [4/4]
MessageBuilder & el::base::MessageBuilder::operator<< (std::ostream &(*)(std::ostream &) OStreamMani) inline
Definition at line 2898 of file easylogging++.h.
References m_logger, and el::Logger::stream().
writeIterator()
template<class Iterator > MessageBuilder & el::base::MessageBuilder::writeIterator (Iterator begin_, Iterator end_, std::size_t size_) inline private
Definition at line 3154 of file easylogging++.h.
References el::base::consts::kMaxLogPerContainer, m_containerLogSeparator, m_logger, and el::Logger::stream().
Field Documentation
m_containerLogSeparator
const base::type::char_t* el::base::MessageBuilder::m_containerLogSeparator private
Definition at line 3151 of file easylogging++.h.
m_logger
template<class Class > Logger* el::base::MessageBuilder::m_logger private
Definition at line 3150 of file easylogging++.h.
The documentation for this class was generated from the following files:
lib/easylogging++.h
lib/easylogging++.cc