jsonToBatProject: el::base::Writer Class Reference
el::base::Writer Class Reference
Main entry point of each logging.
#include <easylogging++.h>
Public Member Functions
Writer (Level level, const char *file, base::type::LineNumber line, const char *func, base::DispatchAction dispatchAction=base::DispatchAction::NormalLog, base::type::VerboseLevel verboseLevel=0)
Writer (LogMessage *msg, base::DispatchAction dispatchAction=base::DispatchAction::NormalLog)
virtual ~Writer (void)
template<typename T >
Writer & operator<< (const T &log)
Writer & operator<< (std::ostream &(*log)(std::ostream &))
operator bool ()
Writer & construct (Logger *logger, bool needLock=true)
Writer & construct (int count, const char *loggerIds,...)
Protected Member Functions
void initializeLogger (const std::string &loggerId, bool lookup=true, bool needLock=true)
void processDispatch ()
void triggerDispatch (void)
Protected Attributes
LogMessage * m_msg
Level m_level
const char * m_file
const base::type::LineNumber m_line
const char * m_func
base::type::VerboseLevel m_verboseLevel
Logger * m_logger
bool m_proceed
base::MessageBuilder m_messageBuilder
base::DispatchAction m_dispatchAction
std::vector< std::string > m_loggerIds
Friends
class el::Helpers
Additional Inherited Members
Private Member Functions inherited from el::base::NoCopy
NoCopy (void)
Detailed Description
Main entry point of each logging.
Definition at line 3190 of file easylogging++.h.
Constructor & Destructor Documentation
Writer() [1/2]
el::base::Writer::Writer (Level level, const char * file, base::type::LineNumber line, const char * func, base::DispatchAction dispatchAction = base::DispatchAction::NormalLog, base::type::VerboseLevel verboseLevel = 0) inline
Definition at line 3192 of file easylogging++.h.
References m_dispatchAction, m_file, m_func, m_level, m_line, m_logger, m_msg, m_proceed, and m_verboseLevel.
Writer() [2/2]
el::base::Writer::Writer (LogMessage * msg, base::DispatchAction dispatchAction = base::DispatchAction::NormalLog) inline
Definition at line 3199 of file easylogging++.h.
References el::LogMessage::level(), m_dispatchAction, m_level, m_line, m_logger, m_msg, m_proceed, and el::Unknown.
~Writer()
virtual el::base::Writer::~Writer (void) inline virtual
Definition at line 3204 of file easylogging++.h.
References processDispatch().
Member Function Documentation
construct() [1/2]
Writer & el::base::Writer::construct (int count, const char * loggerIds, ...)
Definition at line 2538 of file easylogging++.cc.
References el::base::MessageBuilder::initialize(), initializeLogger(), m_logger, and m_messageBuilder.
construct() [2/2]
Writer & el::base::Writer::construct (Logger * logger, bool needLock = true)
Definition at line 2531 of file easylogging++.cc.
References el::Logger::id(), el::base::MessageBuilder::initialize(), initializeLogger(), m_logger, and m_messageBuilder.
initializeLogger()
void el::base::Writer::initializeLogger (const std::string & loggerId, bool lookup = true, bool needLock = true) protected
Definition at line 2557 of file easylogging++.cc.
References el::base::threading::ThreadSafe::acquireLock(), construct(), el::Debug, el::Logger::enabled(), el::base::consts::kDefaultLoggerId, m_file, m_func, m_level, m_line, m_logger, m_proceed, and Writer().
operator bool()
el::base::Writer::operator bool () inline
Definition at line 3227 of file easylogging++.h.
operator<<() [1/2]
template<typename T > Writer & el::base::Writer::operator<< (const T & log) inline
Definition at line 3209 of file easylogging++.h.
References m_messageBuilder, and m_proceed.
operator<<() [2/2]
Writer & el::base::Writer::operator<< (std::ostream &(*)(std::ostream &) log) inline
Definition at line 3218 of file easylogging++.h.
References m_messageBuilder, and m_proceed.
processDispatch()
void el::base::Writer::processDispatch () protected
Definition at line 2585 of file easylogging++.cc.
References m_logger, m_proceed, el::base::threading::ThreadSafe::releaseLock(), el::Logger::stream(), and triggerDispatch().
triggerDispatch()
void el::base::Writer::triggerDispatch (void) protected
Definition at line 2626 of file easylogging++.cc.
References el::base::utils::abort(), construct(), el::base::LogDispatcher::dispatch(), el::base::consts::kDefaultLoggerId, el::base::LogDispatcher::LogDispatcher(), m_dispatchAction, m_file, m_func, m_level, m_line, m_logger, m_msg, m_proceed, m_verboseLevel, el::base::threading::ThreadSafe::releaseLock(), el::Logger::stream(), el::Warning, and Writer().
Friends And Related Symbol Documentation
el::Helpers
friend class el::Helpers friend
Definition at line 3245 of file easylogging++.h.
Field Documentation
m_dispatchAction
base::DispatchAction el::base::Writer::m_dispatchAction protected
Definition at line 3243 of file easylogging++.h.
m_file
const char* el::base::Writer::m_file protected
Definition at line 3236 of file easylogging++.h.
m_func
const char* el::base::Writer::m_func protected
Definition at line 3238 of file easylogging++.h.
m_level
Level el::base::Writer::m_level protected
Definition at line 3235 of file easylogging++.h.
m_line
const base::type::LineNumber el::base::Writer::m_line protected
Definition at line 3237 of file easylogging++.h.
m_logger
Logger* el::base::Writer::m_logger protected
Definition at line 3240 of file easylogging++.h.
m_loggerIds
std::vector<std::string> el::base::Writer::m_loggerIds protected
Definition at line 3244 of file easylogging++.h.
m_messageBuilder
base::MessageBuilder el::base::Writer::m_messageBuilder protected
Definition at line 3242 of file easylogging++.h.
m_msg
LogMessage* el::base::Writer::m_msg protected
Definition at line 3234 of file easylogging++.h.
m_proceed
bool el::base::Writer::m_proceed protected
Definition at line 3241 of file easylogging++.h.
m_verboseLevel
base::type::VerboseLevel el::base::Writer::m_verboseLevel protected
Definition at line 3239 of file easylogging++.h.
The documentation for this class was generated from the following files:
lib/easylogging++.h
lib/easylogging++.cc