.TH "bug" 3 "Wed Feb 28 2024 09:42:02" "Version 0.2.0" "jsonToBatProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 
.PP

.IP "\fBMember \fBmain\fP (int argc, char *argv[])\fP" 1c
Getopt is not working on Windows\&.  
.IP "\fBMember \fButils::StartupHandler::getOptions\fP (int argc, char *argv[])\fP" 1c
 Global verbose flag is not working\&.
.PP

