.TH "src/sources/StartupHandler.cpp" 3 "Wed Feb 28 2024 09:42:02" "Version 0.2.0" "jsonToBatProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sources/StartupHandler.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'StartupHandler\&.hpp'\fP
.br
\fR#include 'easylogging++\&.h'\fP
.br
\fR#include <getopt\&.h>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <stdexcept>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fButils\fP"
.br
.RI "Namespace for utility functions\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static int \fButils::verbose\fP = 0"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for jsonToBatProject from the source code\&.
