.TH "todo" 3 "Wed Feb 28 2024 09:42:02" "Version 0.2.0" "jsonToBatProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
.PP

.IP "\fBMember \fBmain\fP (int argc, char *argv[])\fP" 1c
.IP "\(bu" 2
Remove Debug once getopt is working 
.PP
.IP "\fBMember \fButils::StartupHandler::getOptions\fP (int argc, char *argv[])\fP" 1c
.IP "\(bu" 2
Implement functionality for the options\&.
.IP "\(bu" 2
Implement/Add more options\&.
.IP "\(bu" 2
Shorten function and outsource functionality to other functions\&. 
.PP
.IP "\fBMember \fButils::StartupHandler::initEasyLogging\fP ()\fP" 1c
.IP "\(bu" 2
Improve easylogging configuration 
.PP
.PP

