.TH "utils" 3 "Wed Feb 28 2024 09:42:02" "Version 0.2.0" "jsonToBatProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utils \- Namespace for utility functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStartupHandler\fP"
.br
.RI "Handles startup task for the application\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static int \fBverbose\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Namespace for utility functions\&. 

This namespace contains utility functions for the application\&. Currently, it contains the \fBStartupHandler\fP class\&. 
.SH "Variable Documentation"
.PP 
.SS "int utils::verbose = 0\fR [static]\fP"

.PP
Definition at line \fB16\fP of file \fBStartupHandler\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for jsonToBatProject from the source code\&.
