.TH "WIP" 3 "Wed Feb 28 2024 09:26:16" "Version 0.2.0" "jsonToBatProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WIP
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBexampleEasyLogging\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void WIP::exampleEasyLogging ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for jsonToBatProject from the source code\&.
