JSON2Batch: BatchCreator Class Reference
BatchCreator Class Reference
Creates a batch file from a FileData obeject.
#include <BatchCreator.hpp>
Public Member Functions
BatchCreator (std::shared_ptr< parsing::FileData > fileData)
Initializes the BatchCreator.
std::shared_ptr< std::stringstream > getDataStream () const
Returns the stringstream.
Private Member Functions
void createBatch ()
Creates the batch stream.
void writeStart () const
Wirtes the start of the batch file.
void writeHideShell () const
Writes the visibility of the shell.
void writeCommands () const
Writes the commands to be executed.
void writeEnvVariables () const
Set's environment variables.
void writePathVariables () const
Set's the path variables.
void writeApp () const
If an application is given, it is started at the end.
void writeEnd () const
Writes the end of the batch file.
Private Attributes
std::shared_ptr< std::stringstream > dataStream
std::shared_ptr< parsing::FileData > fileData
Detailed Description
Creates a batch file from a FileData obeject.
Uses a FileData object to create a string stream, which can then be streamed into a batch file.
See also
FileData
Definition at line 29 of file BatchCreator.hpp.
Constructor & Destructor Documentation
BatchCreator()
BatchCreator::BatchCreator (std::shared_ptr< parsing::FileData > fileData) explicit
Initializes the BatchCreator.
Creates a stringstream and calls the createBatch() function
Parameters
filenData A shared pointer to the FileData object
Definition at line 18 of file BatchCreator.cpp.
References createBatch(), and dataStream.
Member Function Documentation
createBatch()
void BatchCreator::createBatch () private
Creates the batch stream.
< FileData object
The method calls all necessary functions to create the stream for the batch file.
Definition at line 26 of file BatchCreator.cpp.
References writeApp(), writeCommands(), writeEnd(), writeEnvVariables(), writeHideShell(), writePathVariables(), and writeStart().
getDataStream()
std::shared_ptr< std::stringstream > BatchCreator::getDataStream () const inline
Returns the stringstream.
Returns
A shared pointer to the stringstream
Definition at line 46 of file BatchCreator.hpp.
References dataStream.
writeApp()
void BatchCreator::writeApp () const private
If an application is given, it is started at the end.
If the key "application" is given in the json file, the application is started at the end of the batch file.
Definition at line 87 of file BatchCreator.cpp.
References dataStream, and fileData.
writeCommands()
void BatchCreator::writeCommands () const private
Writes the commands to be executed.
Writes the commands to be executed from the FileData object. Those originiate from the "commands" entry in the json file
Definition at line 56 of file BatchCreator.cpp.
References dataStream, and fileData.
writeEnd()
void BatchCreator::writeEnd () const private
Writes the end of the batch file.
Writes the end of the batch file, which is always the same:
@ECHO ON
Definition at line 103 of file BatchCreator.cpp.
References dataStream.
writeEnvVariables()
void BatchCreator::writeEnvVariables () const private
Set's environment variables.
Set's the envirment variables for the batch. Those originiate from the "ENV" entry in the json file with the following syntax:
Entry under "key" = Entry under "value"
Definition at line 66 of file BatchCreator.cpp.
References dataStream, and fileData.
writeHideShell()
void BatchCreator::writeHideShell () const private
Writes the visibility of the shell.
This hides/shows the shell after the batch file has been executed
Definition at line 44 of file BatchCreator.cpp.
References dataStream, and fileData.
writePathVariables()
void BatchCreator::writePathVariables () const private
Set's the path variables.
Set's the path variables for the batch. Those originiate from the "PATH" entry in the json file
Definition at line 75 of file BatchCreator.cpp.
References dataStream, and fileData.
writeStart()
void BatchCreator::writeStart () const private
Wirtes the start of the batch file.
Writes the start of the batch file, which is always the same:
setzt ECHO off
startet cmd.exe
Definition at line 38 of file BatchCreator.cpp.
References dataStream.
Member Data Documentation
dataStream
std::shared_ptr<std::stringstream> BatchCreator::dataStream private
Definition at line 52 of file BatchCreator.hpp.
fileData
std::shared_ptr<parsing::FileData> BatchCreator::fileData private
< stringstream for the batch file
Definition at line 54 of file BatchCreator.hpp.
The documentation for this class was generated from the following files:
src/include/BatchCreator.hpp
src/sources/BatchCreator.cpp