// This file is autogenerated. Changes will be overwritten
/**
 * \file config.hpp
 * \author
 * \brief
 * \details
 *
 * \copyright See the LICENSE file.
 */
#ifndef CONFIG_HPP
#define CONFIG_HPP
#define MAJOR_VERSION 0
#define MINOR_VERSION 1
#define PATCH_VERSION 5
#define DESCRIPTION "A simple tool to convert json to batch."
#define PROJECT_NAME "jsonToBatch"
#define AUTHORS "Elena Schwarzbach, Max Rodler, Simon Blum, Sonia Sinaci"
#define HOMEPAGE_URL "https://definitelynotsimon13.github.io/ProjectJsonToBat"
#endif
