/**
 * @file config.hpp
 * @author Simon Blum
 * @date 2024-04-18
 * @version 0.1.5
 * @brief Configures general project information
 * @details
 * This file is used by CMake to configure general information which can be
 * used throughout the project.
 *
 * @note This file is automatically configured by CMake.
 *       The original file can be found in conf/config.hpp.in
 * @license GNU GPLv3
 * @copyright See LICENSE file
 */
// This file is autogenerated. Changes will be overwritten

#ifndef CONFIG_HPP
#define CONFIG_HPP
#define MAJOR_VERSION 0
#define MINOR_VERSION 2
#define PATCH_VERSION 0
#define DESCRIPTION "A simple tool to convert json to batch."
#define PROJECT_NAME "jsonToBatch"
#define AUTHORS "Elena Schwarzbach, Max Rodler, Simon Blum, Sonia Sinaci"
#define HOMEPAGE_URL "https://definitelynotsimon13.github.io/ProjectJsonToBat"
#endif
